### ISSUE TITLE
GetFile extension method error

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/PnP-Sites-Core#1022] opened 2017-01-30 20:15 UTC
_From @icecubemint on June 6, 2016 10:58_

Hello! From the end of the last week I receive the following error when using GetFile() extension method: _Method not found: 'Void Microsoft.SharePoint.Client.ClientRuntimeContext.set_DisableReturnValueCache(Boolean)'. at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay) at Microsoft.SharePoint.Client.FileFolderExtensions.GetFile(Folder folder, String fileName) ._

I'm trying to get a file from folder by name:
 _var fileToUpload = folderToUpload.GetFile(fileName);_

It worked before but now this error is thrown. I tried to update the nuget package but it didn't help.

_Copied from original issue: SharePoint/PnP#1451_

**Comment by VesaJuvonen** [comment] 2017-01-30 20:15
Relocating to Core repository for further check. Most likely already solved issue, but good to double check.

**Comment by jansenbe** [comment] 2017-02-03 09:12
This method is only available in 2016/Online CSOM redist. I assume you're using the wrong CSOM version when working with your SharePoint environment. I'm closing this issue as it's clearly due to a mismatch in sharepoint version versus CSOM version. Feel free to reopen if you can reproduce this using the correct sharepoint / csom version combination.

**Closed by jansenbe** 2017-02-03 09:12 UTC

**Comment by bramdejager** [comment] 2017-03-06 14:38
Hi, I ran into this issue on my local machine. After some digging around I found the resolution. Just wanted to share this with you as some reference when running into the issue yourself. 

**Root cause analysis:** The issue on my machine was caused due to the “SharePoint Client Components” which were installed on my local machine. I think this was installed when installing Visual Studio or Office Developer Tools which install these components by default. 

What actually happens when this is installed on your machine, the Microsoft.SharePoint.Client.dll is installed in your GAC. This is the initial released version which is an old version. 

When debugging your code you can see the assemblies which are loaded for your application (Debug > Windows > Modules). Mine showed loading the Microsoft.SharePoint.Client assemblies from the GAC instead of local DEBUG folder where my console application is executed. 

**Resolution:** uninstall the “SharePoint Client Components” from the Programs and Features. Now the assembly from the DEBUG folder is picked up and your console is using the correct CSOM version (16.0.4351.1000).
