### ISSUE TITLE
Using tokens fails when applying template in SharePoint 2013

### ISSUE THREAD

**Issue by tarjeieo** [SharePoint/PnP-Sites-Core#2015] opened 2018-12-17 16:22 UTC
#### Category
[X ] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[X] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 15.0.5085.1000

#### Expected or Desired Behavior

Applying a template with apply-pnpprovisioningtemplate using tokens, e.g. {site} or {parameter:X}.

This is SP2013 Nov 2018 CU, 15.0.5085.1000.

I have tried this with both PnP PowerShell September 2018 and December 2018. Both fails. I've also tried with provisioning schema 2018/01 and 2018/07.

#### Observed Behavior

I'm attempting to apply a super simple template to a site, but using tokens causes the operation to fail. See following error (1): Value cannot be null. Parameter name: g
![image](https://user-images.githubusercontent.com/1837390/50099983-a828d200-021f-11e9-884d-c0063b1f50f9.png)

While (2) shows the template being applied without tokens - goes right through.

#### Steps to Reproduce

This is a simple template to reproduce this issue. Replacing {site} with /sites/mycustomsite will make it work again.

```
<?xml version="1.0"?>
<pnp:Provisioning 
    xmlns:pnp="http://schemas.dev.office.com/PnP/2018/07/ProvisioningSchema">
	<pnp:Preferences/>
    <pnp:Templates ID="CONTAINER-PP">
        <pnp:ProvisioningTemplate ID="TEMPLATE-TEST" Version="0">
           <pnp:WebSettings SiteLogo="{site}/siteassets/pp/img/ICO-Site-Global-13.png">
			</pnp:WebSettings>
        </pnp:ProvisioningTemplate>
    </pnp:Templates>
</pnp:Provisioning>
```

#### Troubleshooting

Checked ULS, and found an error that lead me to https://blogs.msdn.microsoft.com/vesku/2014/06/09/provisioning-site-collections-using-sp-app-model-in-on-premises-with-just-csom/. However, after applying these changes, we get the same error when applying, but now there are no errors in ULS.

**Comment by wobba** [comment] 2018-12-19 09:36
The issue is related to the `{authenticationrealm}` token where it fails to retrieve the realm guid. I'll try to add a check so that the guid parser doesn't fail for this case - returning an empty guid instead.

**Comment by wobba** [comment] 2018-12-19 11:47
Thank you for reporting this @tarjeieo and the fix will be included in the next release. Have a merry x-mas!🐱‍💻

**Closed by wobba** 2018-12-19 11:47 UTC
