### ISSUE TITLE
Feature '<guid>' for list template '10007' is not installed in this farm

### ISSUE THREAD

**Issue by malexandrum** [SharePoint/PnP-Sites-Core#713] opened 2016-08-19 17:14 UTC
#### Category

[x] Bug
[ ] Enhancement
#### Environment

[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013
#### Expected or Desired Behavior

Get a template and apply it on a new site collection
#### Observed Behavior

When trying to apply an extracted template using Aug release, at some point I get:
`Feature '8d0adeaf-9d5d-424d-9327-27147c9d9030' for list template '10007' is not installed in this farm`

That list template has been deployed to the source site collection using the features framework and the template Id has been set manually in the list template xml in order to differentiate the list from the default Generic List Template.
#### Steps to Reproduce
1. In VS 2013 / 2015 in a no code sandbox solution add a new list based Default (Custom List). 
2. In Elements.xml for list template change Type attribute from "100" to some other value not used by other list templates, for example "10001"
3. In Element.xml for list instance change TemplateType attribute to the above value
4. Install the solution on a target site collection and activate the features in it
5. Get-SPOProvisioningTemplate
6. Apply-SPOProvisioningTemplate to a new site collection
7. Error described

**Comment by jansenbe** [comment] 2017-02-06 01:03
Hi @malexandrum ,

The problem you see is "by design": essentially the provisioning engine is not responsible the 'available' features, it can only activate/deactivate them. In your case you added features using the sandbox solution, exported those and then tried to import them on the target which did not have the sandbox solution activated. If you want to use the engine in these kind of scenarios you'll need to handle the deployment and activation of depending sandbox solutions via additional code or scripting.

Since this is by design I'm closing this issue now.

**Closed by jansenbe** 2017-02-06 01:03 UTC
