### ISSUE TITLE
Get Provisioning Template for 'Promoted Links' list breaks if the list is customised

### ISSUE THREAD

**Issue by backrowbloke** [SharePoint/PnP-Sites-Core#904] opened 2016-12-20 10:55 UTC
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!

#### Category
[ X] Bug
[ ] Enhancement

#### Environment
[ X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
Expected behaviour is that using Get-PNPProvisioningTemplate should export the list and full schema to a template

#### Observed Behavior
Generic error thrown "Cannot complete this action... at Line:1 char:1". Set-PNPTraceLog does not capture any errors.

#### Steps to Reproduce
Create a promoted links list. Add a custom column and a new view based upon the 'Tiles' view
If customised list is removed, export works as exptected

**Comment by erwinvanhunen** [comment] 2017-01-06 14:35
Hi,

I just tried to reproduce this but I don't run into the issues.

I created a promoted list, added an column to the list, a simple text column. Then I created a new view based upon the Tiles view which I called "ExtraTiles", and it successfully exported the template:

```xml
        <pnp:ListInstance Title="Promo" Description="" DocumentTemplate="" TemplateType="170" Url="Lists/Promo" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" TemplateFeatureID="192efa95-e50c-475e-87ab-361cede5dd7f" EnableAttachments="false" EnableFolderCreation="false">
          <pnp:Views>
            <View Name="{FBEDEF9F-7ECF-48E6-884D-D3EBC1BB2D87}" DefaultView="TRUE" MobileDefaultView="TRUE" Type="HTML" ReadOnly="TRUE" OrderedView="TRUE" DisplayName="Tiles" Url="/sites/demo1/Lists/Promo/Tiles.aspx" Level="1" BaseViewID="1" ContentTypeID="0x">
              <Query>
                <OrderBy>
                  <FieldRef Name="TileOrder" Ascending="TRUE" />
                  <FieldRef Name="Modified" Ascending="FALSE" />
                </OrderBy>
              </Query>
              <ViewFields>
                <FieldRef Name="Title" />
                <FieldRef Name="BackgroundImageLocation" />
                <FieldRef Name="Description" />
                <FieldRef Name="LinkLocation" />
                <FieldRef Name="LaunchBehavior" />
                <FieldRef Name="BackgroundImageClusterX" />
                <FieldRef Name="BackgroundImageClusterY" />
                <FieldRef Name="Extra" />
              </ViewFields>
              <RowLimit Paged="TRUE">30</RowLimit>
              <JSLink>sp.ui.tileview.js</JSLink>
            </View>
            <View Name="{237AC287-0451-4812-B8B1-715EBD2685FE}" Type="HTML" OrderedView="TRUE" DisplayName="All Promoted Links" Url="/sites/demo1/Lists/Promo/AllItems.aspx" Level="1" BaseViewID="3" ContentTypeID="0x">
              <Query>
                <OrderBy>
                  <FieldRef Name="TileOrder" Ascending="TRUE" />
                  <FieldRef Name="Modified" Ascending="FALSE" />
                </OrderBy>
              </Query>
              <ViewFields>
                <FieldRef Name="Title" />
                <FieldRef Name="BackgroundImageLocation" />
                <FieldRef Name="Description" />
                <FieldRef Name="LinkLocation" />
                <FieldRef Name="LaunchBehavior" />
                <FieldRef Name="TileOrder" />
              </ViewFields>
              <RowLimit Paged="TRUE">30</RowLimit>
              <JSLink>clienttemplates.js</JSLink>
            </View>
            <View Name="{55ABD3DB-5C4B-40F6-8891-3FFB79D778C9}" Type="HTML" DisplayName="ExtraTiles" Url="/sites/demo1/Lists/Promo/ExtraTiles.aspx" Level="1" BaseViewID="1" ContentTypeID="0x">
              <Query>
                <OrderBy>
                  <FieldRef Name="TileOrder" Ascending="TRUE" />
                  <FieldRef Name="Modified" Ascending="FALSE" />
                </OrderBy>
              </Query>
              <ViewFields>
                <FieldRef Name="BackgroundImageLocation" />
                <FieldRef Name="Description" />
                <FieldRef Name="LinkLocation" />
                <FieldRef Name="LaunchBehavior" />
                <FieldRef Name="BackgroundImageClusterX" />
                <FieldRef Name="BackgroundImageClusterY" />
                <FieldRef Name="Extra" />
              </ViewFields>
              <RowLimit Paged="FALSE">30</RowLimit>
              <JSLink>sp.ui.tileview.js</JSLink>
            </View>
          </pnp:Views>
          <pnp:Fields>
            <Field ID="{a0fc423e-0808-490e-905e-260abd3d6511}" Type="URL" Name="BackgroundImageLocation" DisplayName="Background Image Location" Required="FALSE" SEALED="TRUE" SourceID="http://schemas.microsoft.com/sharepoint/v3" StaticName="BackgroundImageLocation" ColName="nvarchar3" ColName2="nvarchar4" />
            <Field ID="{bced0253-a215-49a2-bcd9-5025ad49560d}" Type="Note" Name="Description" DisplayName="Description" Required="FALSE" SEALED="TRUE" SourceID="http://schemas.microsoft.com/sharepoint/v3" StaticName="Description" ColName="ntext2" />
            <Field ID="{fda2f5e5-8253-4b10-8876-a42268d758e0}" Type="URL" Name="LinkLocation" DisplayName="Link Location" Required="TRUE" SEALED="TRUE" SourceID="http://schemas.microsoft.com/sharepoint/v3" StaticName="LinkLocation" ColName="nvarchar5" ColName2="nvarchar6" />
            <Field ID="{b2424958-fe1e-4227-af83-954985029aac}" Type="Choice" Name="LaunchBehavior" DisplayName="Launch Behavior" Required="TRUE" Format="Dropdown" SEALED="TRUE" SourceID="http://schemas.microsoft.com/sharepoint/v3" StaticName="LaunchBehavior" ColName="nvarchar7">
              <CHOICES>
                <CHOICE>In page navigation</CHOICE>
                <CHOICE>Dialog</CHOICE>
                <CHOICE>New tab</CHOICE>
              </CHOICES>
              <Default>In page navigation</Default>
            </Field>
            <Field ID="{722b3e6d-ebb5-4b1c-8dde-8936e53a40c3}" Type="Number" Name="TileOrder" DisplayName="Order" Required="FALSE" SEALED="TRUE" SourceID="http://schemas.microsoft.com/sharepoint/v3" StaticName="TileOrder" ColName="float1" />
            <Field ID="{2a54fee9-ad68-454b-905b-f92ccee343d3}" Type="Number" Name="BackgroundImageClusterX" DisplayName="Background Image Cluster Horizontal Start" Required="FALSE" SEALED="TRUE" ShowInDisplayForm="FALSE" ShowInEditForm="FALSE" ShowInNewForm="FALSE" SourceID="http://schemas.microsoft.com/sharepoint/v3" StaticName="BackgroundImageClusterX" ColName="float2" />
            <Field ID="{2976fc30-0bbe-4671-bcf1-87679b512e9b}" Type="Number" Name="BackgroundImageClusterY" DisplayName="Background Image Cluster Vertical Start" Required="FALSE" SEALED="TRUE" ShowInDisplayForm="FALSE" ShowInEditForm="FALSE" ShowInNewForm="FALSE" SourceID="http://schemas.microsoft.com/sharepoint/v3" StaticName="BackgroundImageClusterY" ColName="float3" />
            <Field Type="Text" DisplayName="Extra" Required="FALSE" EnforceUniqueValues="FALSE" Indexed="FALSE" MaxLength="255" ID="{658f1243-0f99-4008-bb74-203ba4e63b45}" SourceID="{{listid:Promo}}" StaticName="Extra" Name="Extra" ColName="nvarchar8" RowOrdinal="0" Version="1" />
          </pnp:Fields>
        </pnp:ListInstance>
```

What type of column did you add? Are you extracting from a rootweb or a subweb? 

If you reproduce the error, can you immediately after the error occured enter the following powershell command:

```powershell
$error[0].Exception.StackTrace
```

and paste the results of that here in a reply?

Thanks!

**Comment by backrowbloke** [comment] 2017-01-06 14:54
List is in a subweb
Added 'choice' field
View filters based upon the choice column
If the list is deleted, eveything else is OK with the expected content type warnings etc.
Command is Get-PNPProvisioningTemplate -Handlers Lists -Out d:\temp.xml
Exception is...

```
Get-PnPProvisioningTemplate : Cannot complete this action.
Please try again.
At line:1 char:1
+ Get-PnPProvisioningTemplate -Handlers Lists -Out d:\temp.xml
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPProvisioningTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.GetProvisioningTemplate
```

**$error[0].Exception.StackTrace**

```
at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ExtractObjects(Web web, ProvisioningTemplate template, ProvisioningTemplateCreationInformation creationInfo)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.GetRemoteTemplate(Web web, ProvisioningTemplateCreationInformation creationInfo)
   at SharePointPnP.PowerShell.Commands.Provisioning.GetProvisioningTemplate.ExtractTemplate(XMLPnPSchemaVersion schema, String path, String packageName)
   at SharePointPnP.PowerShell.Commands.Provisioning.GetProvisioningTemplate.ExecuteCmdlet()
   at SharePointPnP.PowerShell.Commands.SPOCmdlet.ProcessRecord()
```
```

**Comment by erwinvanhunen** [comment] 2017-01-06 16:35
Thanks for getting back to me. Another question: the choice field, is it a sitecolumn or a column directly on the list? Just trying to eliminate all variables.

**Comment by backrowbloke** [comment] 2017-01-09 14:06
A choice column applied directly to the list.
Mandatory=false, unique value required=false. Display mode=Drop down. fill in choice = false. Default value=1. Choices = 1;2;3

**Comment by jansenbe** [comment] 2017-03-10 12:56
Hi @backrowbloke ,

Internal testing could not reproduce this. I'm closing this issue now, but feel free to re-open if you still can simulate using the latest version.

testing comments:
Created sub site, promoted links list, choice filed and custom tiles view.
Downloaded template successfully

**Closed by jansenbe** 2017-03-10 12:56 UTC
Labels: Investigation needed
