### ISSUE TITLE
The 'zoneId' argument cannot be null.

### ISSUE THREAD

**Issue by ThreadPitt** [SharePoint/PnP-Sites-Core#1301] opened 2017-08-18 07:26 UTC
#### Category
[x ] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ x] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
August 2017 CU (sts2016-kb4011049-fullfile-x64-glb)

#### Expected or Desired Behavior
ApplyProvisioningTemplate()  succeeds, obviously :-)

#### Observed Behavior
ApplyProvisioningTemplate() fails with error "The 'zoneId' argument cannot be null"

(this happened after I added a standard document library web part to the home page, before the webpart it was working fine!)

#### Steps to Reproduce
Blank Site Template.
one custom list, one custom doc lib (both save some additional standard columns)
Added on the home page a standard web part of the custom document library
(Tried changing zoneId/zoneIndex to no avail.)

**Comment by waaromikniet** [comment] 2017-08-28 11:54
I had the same issue on my SP2013 farm. This was the fix:

https://prairiedeveloper.com/2017/02/field-or-property-timezoneid-does-not-exist/

**Comment by stact** [comment] 2017-09-06 15:07
same issue here. More details with the stack trace:

`System.ArgumentNullException: The 'zoneId' argument cannot be null.
Nom du paramètre : zoneId
   at Microsoft.SharePoint.Client.WebParts.LimitedWebPartManager.AddWebPart(WebPart webPart, String zoneId, Int32 zoneIndex)
   at Microsoft.SharePoint.Client.PageExtensions.AddWebPart(Web fileWeb, File webPartPage, WebPartEntity webPart, String zoneId, Int32 zoneIndex)
   at Microsoft.SharePoint.Client.PageExtensions.AddWebPartToWebPartPage(Web web, String serverRelativePageUrl, WebPartEntity webPart)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectFiles.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo)
   at SitesFactory.SitesFactory.ProvisionPnPSiteTemplate(ProvisioningTemplate template)`

**Comment by VesaJuvonen** [comment] 2018-04-16 11:16
This issue is not caused by PnP, it was caused by native SP2016 CSOM, which did not have ZoneId exposed in CSOM, even though it was exposed in SP2013. This gap has bee now addressed in engineering side and it will be available in upcoming CUs (most likely in May 2018 CU for SP2016). This was really unfortunate SharePoint engineering miss. The property will be there at SP2019, so the issue was only within SP2016. Closing this from this repository as the issue was on the oob CSOM and it has been now finally fixed.

**Closed by VesaJuvonen** 2018-04-16 11:16 UTC

**Comment by bartplessers** [comment] 2018-12-08 01:00
Sorry to come back on this again
Trying to get a template of my **SP2013** site with:

# save site as template
`Get-PnPProvisioningTemplate -Out template.xml -PersistBrandingFiles -PersistPublishingFiles`

and receive same error:
```

```
> Get-PnPProvisioningTemplate : The property or field 'ZoneId' has not been initialized. It has not been requested or the request has not been executed. It 
> may need to be explicitly requested.
> At line:14 char:1
> + Get-PnPProvisioningTemplate -Out template.xml -PersistBrandingFiles - ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : WriteError: (:) [Get-PnPProvisioningTemplate], PropertyOrFieldNotInitializedException
>     + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Site.GetProvisioningTemplate
```

```

If I take a look at logs at
Set-PnPTraceLog -On -LogFile "C:\DATA\PROJECTS\PnP\log\log.xml" -Level Debug

that gives me not much information.


Any suggestions
