### ISSUE TITLE
Cannot save a page that has full-width column section.

### ISSUE THREAD

**Issue by AriGunawan** [SharePoint/PnP-Sites-Core#1304] opened 2017-08-21 03:04 UTC
Hi,
I'm getting error when trying to save a page that has full-width column section.
Is there any other ways to update this page from code? Thanks.

#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
The page should be saved.

#### Observed Behavior
When the code tried to save a page that has full-width column section.
It got this exception message: "**You cannot host this web part inside a one column full width zone, only an image web part or hero web part are allowed**". Even though we have an image web part or hero web part inside the full-width column section.

#### Steps to Reproduce
1. Create a modern page.
1. Add full-width column section.
1. Insert an image web part or hero web part to the section.
1. Try to update the page from a console app using SharePointPnPCoreOnline

#### Sample Code
```
using (var clientContext = new ClientContext(targetWebUrl))
{
    clientContext.Credentials = new SharePointOnlineCredentials(userName, password);
    clientContext.RequestTimeout = Timeout.Infinite;

    try
    {
        var page = OfficeDevPnP.Core.Pages.ClientSidePage.Load(clientContext, pageName);
        page.Save(); // failed when executing this method
        page.Publish();
    }
    catch (Exception ex)
    {
        Console.WriteLine($"Failed to save {pageName}: {ex.Message}");
    }
}
```

**Comment by jansenbe** [comment] 2017-08-21 07:00
Hi @AriGunawan, what you see is by design as full-width pages are only meant to work in communication sites. If you can reproduce the issue with a communication site then please re-open this issue.

**Comment by AriGunawan** [comment] 2017-08-21 08:13
Hi @jansenbe,
Yes, the issue happened in communication site.

**Comment by jansenbe** [comment] 2017-08-21 16:28
Hi @AriGunawan,

I did some testing and indeed was able to repro the issue. It has been fixed in the dev tree and will end up in the September release. Thanks for reporting this.

**Closed by jansenbe** 2017-08-21 16:28 UTC

**Comment by eBehbahani** [comment] 2018-09-24 22:37
Hello @jansenbe!

I recently started experimenting with the full-width webparts and deploying them via powershell. I'm seeing the same issue as @AriGunawan after having installed the latest verison of SharePoint PnP PowerShell (ver. 3.1.1809.0). 

I've added the `"supportsFullBleed": true` to my webpart manifest. I then run the following code: 
`Add-PnPClientSidePageSection -Page $page -SectionTemplate OneColumnFullWidth`
`Add-PnPClientSideWebPart -Page $page -Section 1 -Column 1 -Component PageHeader	`
`Set-PnPClientSidePage -Identity $pageName -CommentsEnabled:$false -Publish `

And get the following error:
`Set-PnPClientSidePage : You cannot host this web part inside a one column full width section, only webparts that support full bleed are allowed`

When I navigate to the page, I see all the webparts have been added and I can manually press the publish button to publish the page.   

Would this fix have covered the issue that I am seeing?

**Comment by jansenbe** [comment] 2018-09-25 06:36
Hi @eBehbahani ,

Back in August 2017 this was about the 1st party web parts that support full bleed, not about third party web parts as that back then was not yet possible. This seems to be a bug we need to address. Can you open a new issue and describe the issue (like you did above). We'll then add that to our backlog to get fixed. If you can fix it yourself and provide a PR then that would even be better :-)

**Comment by premiimt20** [comment] 2020-08-28 07:49
Hi All,
I am having same issue. it is happing in communication site while adding second(in loop) onecolumnfullwidth section to page. 
Getting error: you cannot host this web part inside a one column full width section, only web parts that support full bleed are allowed programmatically
I am using CSOM code to add onecolumnfullwidth section
 CanvasSection section = new CanvasSection(page, CanvasSectionTemplate.OneColumnFullWidth, page.Sections.Count + 1);
page.Sections.Add(section);
 page.Save();
page.AddControl(WebPart,section.Columns[0]);
 page.Save();
It is throwing issue while trying to add another onecolumnfullwidth section to page 
Please let me know if there is any solution.
