### ISSUE TITLE
Add support for extraction and activation of OOTB features

### ISSUE THREAD

**Issue by PascalStrassl** [SharePoint/PnP-Sites-Core#1037] opened 2017-02-01 15:01 UTC
#### Category
[ ] Bug
[X] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[X] SharePoint 2016
[X] SharePoint 2013

If SharePoint on-premises, what's exact CU version: SP2013 SP1 - December 2016

#### Expected or Desired Behavior
If you add the FeatureHandler, the activated features should be listed in the template according to the initial template site. So if a new site is being provisioned and the template applied, All features of the template site and target site have the same features activated. 

Optional: add a new property in "ProvisioningTemplateCreationInformation" similar to "IncludeSiteGroups" like "IncludeBaseTemplateFeatureActivations" so that the activation of ootb features is optional and current behaviour still can be applied.

#### Observed Behavior
Only custom features are added to the template. If you use e.g. STS#0 changes in the OOTB features like "minimal download strategy" will be ignored.

**Comment by jansenbe** [comment] 2017-02-03 08:09
Hi pascal,

We by design filter out everything that's delivered by the site's base template. If you don't want that behavior you can always either remove the base template reference when extracting the site (see https://github.com/SharePoint/PnP-Sites-Core/blob/dev/Core/OfficeDevPnP.Core.Tests/Framework/Providers/BaseTemplateTests.cs#L206 for sample code) or programmatically add the feature references in the domain model you got from the engine and then persist it.

Will be closing this issue now.

**Closed by jansenbe** 2017-02-03 08:09 UTC
