### ISSUE TITLE
Provisioning directories recursivity issue

### ISSUE THREAD

**Issue by PierreBiname** [SharePoint/PnP-Sites-Core#716] opened 2016-08-23 12:38 UTC
PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core (OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.DirectoryExtensions)

**#### Category**
[X] Bug
[ ] Enhancement

**#### Environment**
[X] Office 365 / SharePoint Online
[X] SharePoint 2016
[X] SharePoint 2013

**#### Expected or Desired Behavior**
Provision directories in SharePoint

**#### Observed Behavior**
Below the directory structure
-- Assets
---- CS
---- JS
---- IMG

Below what the provisionning engine understand:
-- Assets
---- CS
------ JS
-------- IMG

**#### Steps to Reproduce**
Provisioning Directories with sub directories using the pnp xml tempalte definition.

**#### Submission Guidelines**

The bug is in the **OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.DirectoryExtensions** class in the method **GetDirectoryFiles** (file: OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectFiles.cs).

The code in the line **447** should be some think like below:

```
if (directory.Recursive)
{
    var subFolders = directory.ParentTemplate.Connector.GetFolders(directory.Src);
    var src = directory.Src;
    var folder = directory.Folder;
    foreach (var folder in subFolders)
    {
        directory.Src = src + @"\" + folder;
        directory.Folder = folder  + @"\" + folder;
         result.AddRange(directory.GetDirectoryFiles(metadataProperties));
     }
} 
```

instead of  

```
if (directory.Recursive)
{
    var subFolders = directory.ParentTemplate.Connector.GetFolders(directory.Src);
    foreach (var folder in subFolders)
    {
        directory.Src += @"\" + folder;
        directory.Folder += @"\" + folder;
        result.AddRange(directory.GetDirectoryFiles(metadataProperties));
    }
}
```

Folders of the sames level are added like sub folder of the previous one.

Regards,

Pierre

**Comment by erwinvanhunen** [comment] 2016-09-07 14:59
I just tried, but am unable to reproduce this. Can you provide me a snippet of your template where you define the folders?

**Comment by PierreBiname** [comment] 2016-09-07 15:41
Dear Erwin, 

Thank you for your answer.
Are you sure that you tested with 2 sub folders by folder?
Because I've just tried now with the following file structure :
![image](https://cloud.githubusercontent.com/assets/13751241/18318133/b2eb87de-7520-11e6-91b9-42d906dce9db.png)

Here the xml snippet ;
```
<pnp:Directory Src="Template\Resources" Folder="Style%20Library" Overwrite="true"
            Recursive="true" MetadataMappingFile="None" />
```

Find below the error:
![image](https://cloud.githubusercontent.com/assets/13751241/18318389/d5ce0bc2-7521-11e6-8699-6495892e7912.png)
As you can see, the engine try to find the folder "Test01" in "Test" instead of in the folder "Resources".
Because of the code that I show in my first post.



Also if you let the property "MetadataMappinFile" empty, en erro occured 
![image](https://cloud.githubusercontent.com/assets/13751241/18318259/55e81060-7521-11e6-8a51-0a6d068506d0.png)

Regards,

Pierre

**Comment by rajajii** [comment] 2016-09-28 18:03
I can confimr this issue

**Comment by PaoloPia** [comment] 2017-01-29 16:34
Hi,
Thanks for your feedback this issue have been close a while ago, and we left this issue open. I will close it now. Thanks.

**Closed by PaoloPia** 2017-01-29 16:34 UTC
