### ISSUE TITLE
Get-PnPProvisioningTemplate returns Error 403 SP2013 on premises

### ISSUE THREAD

**Issue by pdecrocq** [SharePoint/PnP-Sites-Core#1064] opened 2017-02-17 16:20 UTC
#### Category
[ ] Issue

#### Environment
[ ] SharePoint 2013 on premises

If SharePoint on-premises, what's exact CU version: don't know how to get this

#### Commands issued
Connect-PnPOnline -UseWebLogin -Url Https://...... (success)
Get-PnPList (success)
Get-PnPProvisioningTemplate -Out D:\PnPCmdlet\Template.pnp (Error)

#### Results
Get-PnPProvisioningTemplate : Le serveur distant a retourné une erreur : (403) Interdit.
Au caractère Ligne:1 : 1
+ Get-PnPProvisioningTemplate -Out D:\PnPCmdlet\Template.pnp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPProvisioningTemplate], WebException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.GetProvisioningTemplate

#### Stacktrace
$error[0].Exception.Stacktrace
   à System.Net.HttpWebRequest.GetResponse()
   à Microsoft.SharePoint.Client.SPWebRequestExecutor.Execute()
   à Microsoft.SharePoint.Client.ClientContext.GetFormDigestInfoPrivate()
   à Microsoft.SharePoint.Client.ClientContext.EnsureFormDigest()
   à Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   à Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
   à OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectRegionalSettings.ExtractObjects(Web web, ProvisioningTemplate template, ProvisioningTemplateCreationInformation creat
ionInfo)
   à OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.GetRemoteTemplate(Web web, ProvisioningTemplateCreationInformation creationInfo)
   à SharePointPnP.PowerShell.Commands.Provisioning.GetProvisioningTemplate.ExtractTemplate(XMLPnPSchemaVersion schema, String path, String packageName)
   à SharePointPnP.PowerShell.Commands.Provisioning.GetProvisioningTemplate.ExecuteCmdlet()
   à SharePointPnP.PowerShell.Commands.PnPCmdlet.ProcessRecord()

#### Expected or Desired Behavior
I would have expected the command to output the source site structure to the specified file

#### Observed Behavior
See results and Stacktrace above

#### Steps to Reproduce
Issue commands against our internal on premises SP2013 platform

**Comment by biste5** [comment] 2017-02-20 14:25
Which authentication providers are enabled on your web application?

It can be a duplicate of #615

**Comment by pdecrocq** [comment] 2017-02-20 17:25
Thanks for your answer. I don't know how to check that. Could you help me ?

**Comment by pdecrocq** [comment] 2017-02-23 16:19
Hello, Anyone here ?

**Comment by biste5** [comment] 2017-02-23 16:45
https://blogs.msdn.microsoft.com/psssql/2011/02/22/sharepoint-adventures-how-to-identify-if-you-are-using-claims-authentication/

First result googling "how to check authentication providers sharepoint 2013"

If UseClaimsAuthentication returns true, then the issue you're running into is the same I reported. If false, then it's likely about something else.

**Comment by pdecrocq** [comment] 2017-02-25 15:59
HI,
Thanks for pointer. I'm sorry but I'm probably a bit novice and "Get-SPWebApplication" doesn't exist in my PowerShell. Any clue on how to install it ?

**Comment by biste5** [comment] 2017-02-26 09:49
there's also the option to check by accessing Central Admin via browser, so if you know its address that maybe an easier path. For executing those PoSh commands you'll have to execute them from a 'SharePoint PowerShell Management Window' (as administrator) which should be available indeed on machines where SharePoint Server is installed

**Comment by pdecrocq** [comment] 2017-02-27 10:32
Well, thanks for answering, "biste5". The thing is that ..
- I'm not site collection admin (just that site full control user) so I cannot go to Central Admin.
- I'm working from my workstation where I don't have things such as "SharePoint PowerShell Management Window".  I.e. SharePoint is not installed on the PC (which is a workstation, not a server) I'm using.
Still, any means to get the needed information ?

**Comment by biste5** [comment] 2017-02-27 11:26
No. You need to ask assistance from the farm administrator.

**Comment by pdecrocq** [comment] 2017-02-27 15:53
Thanks. I have a raised a request to farm admins. I'll let you know.

**Comment by pdecrocq** [comment] 2017-03-02 07:55
Still chasing farm admins to get the information.

**Comment by pdecrocq** [comment] 2017-03-20 17:37
Farm admins refuse to give me the information. Any trick I can use to get it without them ? I'm stuck !

**Comment by Pieter-Veenstra** [comment] 2017-03-20 17:40
I had the same issue earlier today: 

https://veenstra.me.uk/2017/03/20/office-365-office-dev-pnp-powershell-mixing-up-releases/

Can you enable debug with 
Set-PnPTraceLog -On -Level Debug

Then rerun the Get Cmdlet. You might find that the error occurs on the pagecontent.

**Comment by pdecrocq** [comment] 2017-03-21 13:08
Thanks I will give it a try and report.

**Comment by pdecrocq** [comment] 2017-03-22 09:40
Thanks again.
Attached is the generated log. Any clue of what's happening ?
[PnpProvisioningTestLog.txt](https://github.com/SharePoint/PnP-Sites-Core/files/860952/PnpProvisioningTestLog.txt)

**Comment by Pieter-Veenstra** [comment] 2017-03-22 09:50
This problem is different. I can see that there is a problem with the export of the first SharePoint list that it finds.

Can you run the following:
$web = Get-PnPWeb
$web.Context.Load($web.Lists)
$web.Context.ExecuteQuery()
$web.Lists

It looks like there is something causing a problem with the first list that is found.

**Comment by pdecrocq** [comment] 2017-03-22 10:25
Thanks a lot for help.
Here are the results.
[PnpLog.txt](https://github.com/SharePoint/PnP-Sites-Core/files/861090/PnpLog.txt)

**Comment by pdecrocq** [comment] 2017-06-23 07:31
Any comment someone ?

**Comment by spdevdocs** [comment] 2018-04-28 14:00
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*

**Closed by spdevdocs** 2018-04-28 14:00 UTC
Labels: waiting-for-clarification
