### ISSUE TITLE
ApplyProvisioningTemplate fails on SP2013 on-prem when target site doesn't have default groups created

### ISSUE THREAD

**Issue by panjkov** [SharePoint/PnP-Sites-Core#606] opened 2016-06-07 08:51 UTC
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

_You can delete this section after you have confirmed target repository for your submission._
#### Category

[ ] Bug
#### Environment

[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: Apr 2015 CU
#### Expected or Desired Behavior

When ApplyProvisioningTemplate is called on Site Collection that does not have groups set up (i.e. if it is created by CSOM) - default groups should be created
#### Observed Behavior

Groups are not created and the exception is raised: 
Microsoft.SharePoint.Client.ServerObjectNullReferenceException was unhandled
  HResult=-2146233079
  Message=Object reference not set to an instance of an object on server. The object is associated with property AssociatedOwnerGroup.
  Source=Microsoft.SharePoint.Client.Runtime
  StackTrace:
       at Microsoft.SharePoint.Client.ClientObject.CheckUninitializedProperty(String propName)
       at Microsoft.SharePoint.Client.Principal.get_Title()
       at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.TokenDefinitions.AssociatedGroupToken.GetReplaceValue()
       at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.TokenParser.ParseString(String input, String[] tokensToSkip)
       at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.TokenParser.ParseString(String input)
       at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectSiteSecurity.<>c__DisplayClass2_4.<ProvisionObjects>b__4(Group g)
       at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
       at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectSiteSecurity.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)
       at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo)
       at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation)
#### Steps to Reproduce
1. Create new Site using tenant.CreateSite(properties); 
2. Extract template from existing site (STS#0)
3. Call ApplyProvisioningTemplate on newly created site - it will trigger an exception.

[PnPProvisioningDemo.zip](https://github.com/OfficeDev/PnP-Sites-Core/files/302159/PnPProvisioningDemo.zip)

**Comment by nhadro** [comment] 2016-10-24 20:33
Did you ever find a resolution for this?  I'm getting this when I break inheritance on my template.

**Comment by nhadro** [comment] 2016-10-24 22:07
I think the issue is that the default "Owner", "Member", "Visitor" groups are not getting provisioned so when it tries to apply the Roles it blows up.  Is there any reason why these are not getting provisioned?

**Comment by PaoloPia** [comment] 2017-01-28 16:06
Hi Dragan,
Thanks for your feedback. As @nhadro said you should create the groups before applying the template. We can eventually consider adding a flag to the template, in order to create the groups if they are missing, but I think this is not a goal of the engine or a task that targets the engine. As said, I would create the groups before applying the template. I will close this item, but feel free to ask me to re-open it if you find any further issue or you have any additional information. Thanks.

**Closed by PaoloPia** 2017-01-28 16:06 UTC

**Comment by stevebeauge** [comment] 2017-06-19 21:32
Hello,

I'm facing the same issue.

I think the engine should handle the three associated groups provisioning.

In my case, and I guess it's a quite common case, the provisioning engine is used in a solution deployment (in functional terms, not meaning WSP files).

Basically, the process is to create, from a script, a site collection then applying the template.

Your answer mean that you have to create the groups between these two steps (either by script or manually).  Why wouldn't we also provision these groups ?

Moreover I believe these associated groups are, in fact, a user settings, since it's a form that appears after creating the site. Name of these groups may have a functional meaning too.

(hoping I'm clear).

Thanks
