### ISSUE TITLE
A field added to a list shouldn't be added to content types 

### ISSUE THREAD

**Issue by stevebeauge** [SharePoint/PnP-Sites-Core#1353] opened 2017-09-21 10:19 UTC
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[X] SharePoint 2013

#### Expected or Desired Behavior

A field can be added to a list, without adding it to all content types (there's a checkbox for that in the SP UI).

When provisioning local fields using the Pnp engine, the fields shouldn't be added to the content types unless it was specified in the site used when exporting.

#### Observed Behavior

Local fields are always added to all content types in the list, even if the content type does not refers the field.

#### Steps to Reproduce

In the source site:

1. Create a list "some list" based on a generic list
1. Create a site content type "Some content type"
1. Enable CT management in the list
1. Add the "Some content type" CT to the list
1. Delete the Element content type
1. Add a local field to the list "Not in content type". Ensuse the checkbox "Add to all content types" is **not** checked
1. Export the site as template, using `Get-PnPProvisioningTemplate -Out c:\temp\pnp.xml
-handlers fields,lists,contenttypes`

At this point, the template should contains (I removed other artefacts):

````
<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2017/05/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.19.1710.0, Culture=neutral, PublicKeyToken=null" />
  <pnp:Templates ID="CONTAINER-TEMPLATE-BCE23B0BC20F49759271D6AD107D1B40">
    <pnp:ProvisioningTemplate ID="TEMPLATE-BCE23B0BC20F49759271D6AD107D1B40" Version="1" BaseSiteTemplate="STS#0" Scope="RootSite">
      <pnp:ContentTypes>
        <pnp:ContentType ID="0x010026D1CAA1F4DF694C89BE46D339AE18B8" Name="Some content type" Description="" Group="Debug" NewFormUrl="" EditFormUrl="" DisplayFormUrl="">
          <pnp:FieldRefs>
            <pnp:FieldRef ID="c042a256-787d-4a6f-8a8a-cf6ab767f12d" Name="ContentType" />
            <pnp:FieldRef ID="fa564e0f-0c70-4ab9-b863-0177e6ddd247" Name="Title" Required="true" />        
          </pnp:FieldRefs>
        </pnp:ContentType>
     </pnp:ContentTypes>
      <pnp:Lists>
        <pnp:ListInstance Title="Some list" Description="" DocumentTemplate="" TemplateType="100" Url="Lists/1st Case" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" TemplateFeatureID="00bfea71-de22-43b2-a848-c05709900100" ContentTypesEnabled="true" EnableFolderCreation="false" DefaultDisplayFormUrl="{site}/Lists/1st Case/DispForm.aspx" DefaultEditFormUrl="{site}/Lists/1st Case/EditForm.aspx" DefaultNewFormUrl="{site}/Lists/1st Case/NewForm.aspx" ImageUrl="/_layouts/15/images/itgen.png?rev=23" ValidationFormula="" ValidationMessage="">
          <pnp:ContentTypeBindings>
            <pnp:ContentTypeBinding ContentTypeID="0x010026D1CAA1F4DF694C89BE46D339AE18B8" Default="true" />
            <pnp:ContentTypeBinding ContentTypeID="0x0120" />
          </pnp:ContentTypeBindings>
          <pnp:Views>
            <View Name="{3141183C-1CAD-431A-84F8-DE45DD6D6CBC}" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" Type="HTML" DisplayName="Tous les éléments" Url="/sites/pnpcthiddenfields/Lists/1st Case/AllItems.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/generic.png?rev=23">
              <Query>
                <OrderBy>
                  <FieldRef Name="ID" />
                </OrderBy>
              </Query>
              <ViewFields>
                <FieldRef Name="LinkTitle" />
                <FieldRef Name="NotInContentType" />
              </ViewFields>
              <RowLimit Paged="TRUE">30</RowLimit>
              <JSLink>clienttemplates.js</JSLink>
            </View>
          </pnp:Views>
          <pnp:Fields>
            <Field Type="Text" DisplayName="Not in a content type" Required="FALSE" EnforceUniqueValues="FALSE" Indexed="FALSE" MaxLength="255" ID="{78698283-db53-488b-8a8b-c097c8a29026}" SourceID="{{listid:1st Case}}" StaticName="NotInContentType" Name="NotInContentType" ColName="nvarchar5" RowOrdinal="0" Version="1" />
          </pnp:Fields>
        </pnp:ListInstance>
 
      </pnp:Lists>
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>
````

1. Apply the template to a new site

In the "Some list" parameters, you can see that the field "Not in content type" **is** added to the content type "Some content type"

**Comment by PaoloPia** [comment] 2017-10-05 05:12
I just merged the related fix https://github.com/SharePoint/PnP-Sites-Core/pull/1354. Thus, I will close this item.

**Closed by PaoloPia** 2017-10-05 05:12 UTC

**Comment by dsimoes** [comment] 2017-11-16 17:03
@PaoloPia We discovered a regression with this code change (we think) for existing schemas.
What happens is the fields added to Lists that DO NOT have content types enabled (simple lists) will not appear on the list forms since they are not associated with the default content type.

Looking at the code for the fix, you blindly added the AddFieldOptions.AddToNoContentType flag regardless if the list was with content types enabled or not. Most of the simple list schemas just add the default Item/Folder ContentTypeBinding.

If the code change is correct then all the schemas for this use-case need to be changed ? what is the solution for this?

**Comment by stevebeauge** [comment] 2017-11-16 17:08
@dsimoes : can you provide a small repro template? as I'm the author of the evil commit, I could spend some time to fix it.

**Comment by dsimoes** [comment] 2017-11-16 17:33
@stevebeauge Thanks for your help. Here it is below:

`<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2015/12/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.0.1601.0, Culture=neutral, PublicKeyToken=null" />
  <pnp:Templates ID="CONTAINER-ARTIFACTS">
    <pnp:ProvisioningTemplate ID="ARTIFACTS" Version="1">
      <pnp:Lists>
		<pnp:ListInstance Title="Sample" Description="" DocumentTemplate="" TemplateType="100" Url="Lists/Sample" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" TemplateFeatureID="00bfea71-de22-43b2-a848-c05709900100" EnableFolderCreation="false">
		  <pnp:ContentTypeBindings>
			<pnp:ContentTypeBinding ContentTypeID="0x01" Default="true" />
			<pnp:ContentTypeBinding ContentTypeID="0x0120" />
		  </pnp:ContentTypeBindings>
		  <pnp:Views>
			<View Name="{F2511C04-B302-4B11-9EF5-C96956CB49AA}" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" Type="HTML" DisplayName="All Items" Url="/testsite/Lists/Sample/AllItems.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/generic.png?rev=23">
			  <Query>
				<OrderBy>
				  <FieldRef Name="ID" />
				</OrderBy> 
			  </Query>
			  <ViewFields>
				<FieldRef Name="LinkTitle" />
				<FieldRef Name="Link" />
				<FieldRef Name="ItemOrder" />
			  </ViewFields>
			  <RowLimit Paged="TRUE">30</RowLimit>
			  <JSLink>clienttemplates.js</JSLink>
			</View>
		  </pnp:Views>
		  <pnp:Fields>
			<Field Type="URL" DisplayName="Link" Required="TRUE" EnforceUniqueValues="FALSE" Indexed="FALSE" Format="Hyperlink" ID="{f1d2040d-aa9f-44af-be99-a4d8371519d1}" SourceID="{{listid:Sample}}" StaticName="Link" Name="Link" ColName="nvarchar3" RowOrdinal="0" ColName2="nvarchar4" RowOrdinal2="0" />
			<Field Type="Number" DisplayName="ItemOrder" Required="TRUE" EnforceUniqueValues="FALSE" Indexed="FALSE" Decimals="0" ID="{13e850fb-0f76-4c62-b6b4-d2d6517ad6dd}" SourceID="{{listid:Sample}}" StaticName="ItemOrder" Name="ItemOrder" ColName="float1" RowOrdinal="0" />
		  </pnp:Fields>
		</pnp:ListInstance>
      </pnp:Lists>
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>`

**Comment by stevebeauge** [comment] 2017-11-17 15:12
I investigate a bit this issue.
You were right regarding the `AddFieldOptions` but the actual issue is that the provisioning engine does not handle list local content types. 

I created #1457 to illustrate this behavior.
