### ISSUE TITLE
Issue with provisioning a site with OfficedevPnp since Friday June 17th

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/PnP-Sites-Core#770] opened 2016-09-23 12:57 UTC
_From @angelanouwens on June 22, 2016 12:2_

Hi all,

We deploy certain SharePoint Online sites with the help of OfficedevPnp. This always worked fine and last Thursday we have created several sites with it. On Friday however something probably changed we now get an error.
We use the schema's of OfficeDev from august 2015 so maybe it's just outdated but would like the confirmation that installing OfficedevPnp actually does solve the issue we are experiencing since friday.
The error we get starts with [List instances Data Rows] [1] [Error] Creating listitem failed: exception from HRESULT: 0x80131904: at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)......
And gives:
"Error during provisioning of template Lists.xml - Error

Anybody any experience with this or does anyone knows it something changed on SharePoint Online which causes OfficeDevPnP to fail?

Like to know more.

_Copied from original issue: OfficeDev/PnP#1465_

**Comment by VesaJuvonen** [comment] 2016-09-23 12:57
_From @kbarret3 on June 23, 2016 12:11_

+1 from me. We too are experiencing the same issue that started occurring about the same time.

**Comment by VesaJuvonen** [comment] 2016-09-23 12:57
_From @angelanouwens on June 23, 2016 13:53_

@kbarret3  which version of devPnP are you using? also an older version ?

**Comment by VesaJuvonen** [comment] 2016-09-23 12:57
_From @kbarret3 on June 23, 2016 22:40_

Hi @angelanouwens. Yes my code base was I think on the first release that included the capability to provision a site based on a template site. The OfficeDevPnPCore package is at version 1.3.0615.0

**Comment by VesaJuvonen** [comment] 2016-09-23 12:57
_From @angelanouwens on June 24, 2016 8:24_

Thanks for your reaction. We are currently very busy working on the issue and probably updaten devPnP as soon as possible to see if this solves the issue.
Will keep you updated when we have found a solution

**Comment by VesaJuvonen** [comment] 2016-09-23 12:57
_From @johnsandersnl on July 26, 2016 8:21_

+1 We have the same issue/error. Also the schema from august 2015.

**Comment by VesaJuvonen** [comment] 2016-10-05 07:24
We would need assistance on testing this with newer version of the engine and schema.

**Comment by VesaJuvonen** [comment] 2016-10-05 07:25
Hi  @angelanouwens or @johnsandersnl,
any change you could share the actual template you are using or a variation around that, so that we can solve the issue in the engine. thx.

**Comment by johnsandersnl** [comment] 2016-10-10 12:04
Hi Vesa. Thanks for your reply. However, I am not able to help since the templates are no longer accessible by me. I think you can close this issue since it can no longer be reproduced.

**Comment by PaoloPia** [comment] 2017-01-29 18:33
Based on the previous thread, I will close this item.

**Closed by PaoloPia** 2017-01-29 18:33 UTC
