### ISSUE TITLE
Provisioning Engine - Calculated fields not working

### ISSUE THREAD

**Issue by TVDKoni** [SharePoint/PnP-Sites-Core#655] opened 2016-06-30 21:31 UTC
PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
[X ] Bug
[X ] Office 365 / SharePoint Online

Working with dev branch:
SHA-1: fc7289c3b81e83ffea741a497fa8188fd40ff692

I have a content type with 4 calculated fields. One of them looks like:
`<Field ID="{83C16613-9908-4C3C-BA08-A39D582E3C06}" Name="EibCoachText" StaticName="EibCoachText" DisplayName="{resource:SiteColEibCoachTextDisplayName}" Description="{resource:SiteColEibCoachTextDescription}" Group="EiB TN Aktuell" Type="Calculated" ReadOnly="TRUE" ><Formula>=EibCoach</Formula><FieldRefs><FieldRef Name="EibCoach" ID="{4CCD7314-7E66-4BB0-9957-445E4E96169C}" /></FieldRefs></Field>`

If I check the site fields after the deployment, all look ok. They are also attached to the content type. If I add the content type to a list, only one list column for one of the site fields is created. If I check the calculated field in the list column, I see there not the display name from EibCoach like on the site filed, I see the internal name.
i've tried also using display names in the formula, may then i get a #NAME? in the site fields. So it looks better with the internal names. Except the list issue.
If I remove the site field which was created as list column from the content type and attach the content type again to a list, the next calculated column gets created. Always only one. And I'm also not able to add any new calculated column to the list. i always get internal errors.

Can one help? How do I have to define the formula and the FieldRefs correctly?

**Comment by TVDKoni** [comment] 2016-06-30 22:27
Also tried with latest commits from 
SHA-1: 8c9e86687b945e3103c47435920d939f5041d6e4
No success

**Comment by TVDKoni** [comment] 2016-07-01 07:19
Also tried with constant values in the calculated fields without any reference to a column and run into the same issue. So it looks like calculated fields get somehow corrupt!

**Comment by jansenbe** [comment] 2016-07-05 18:05
Hi, 

Can you try with below like XML. This works in our test cases for adding and updating a calculated field

```XML
<!-- Initial create -->
    <Field ID="{00ecca45-2dc2-447a-b722-633fe69a4c6f}" Type="Calculated" Name="FLD_41" DisplayName="Fld 41" Group="PnP Demo" EnforceUniqueValues="FALSE" Indexed="FALSE" Format="DateOnly" LCID="1033" ResultType="Text" ReadOnly="TRUE">
      <Formula>=FLD_1+FLD_2</Formula>
      <FieldRefs>
        <FieldRef Name="FLD_1" ID="{23203E97-3BFE-40CB-AFB4-07AA2B86BF45}" />
        <FieldRef Name="FLD_2" ID="{B01B3DBC-4630-4ED1-B5BA-321BC7841E3D}" />
      </FieldRefs>
    </Field>
​
<!-- Update -->
    <Field ID="{00ecca45-2dc2-447a-b722-633fe69a4c6f}" Type="Calculated" Name="FLD_41" DisplayName="Fld 41" Group="PnP Demo" EnforceUniqueValues="FALSE" Indexed="FALSE" Format="DateOnly" LCID="1033" ResultType="Text" ReadOnly="TRUE">
      <Formula>=FLD_1+FLD_2+FLD_35</Formula>
      <FieldRefs>
        <FieldRef Name="FLD_1" ID="{23203E97-3BFE-40CB-AFB4-07AA2B86BF45}" />
        <FieldRef Name="FLD_2" ID="{B01B3DBC-4630-4ED1-B5BA-321BC7841E3D}" />
        <FieldRef Name="FLD_35" ID="{ebd16147-9087-4b80-b100-028193ee3d23}" />
      </FieldRefs>
    </Field>
```

**Comment by erwinvanhunen** [comment] 2016-09-07 15:58
@TVDKoni any feedback on the reply from @jansenbe? Does the issue still stand?

**Comment by PaoloPia** [comment] 2017-01-28 17:09
Hi @TVDKoni, 
Because we didn't get any feedback in the last 4 months, I assume that the issue is now solved and I will close this item. Please let us know in case of any further need. Thanks.

**Closed by PaoloPia** 2017-01-28 17:09 UTC

**Comment by jansenbe** [comment] 2017-02-03 07:07
**internal testing feedback:**

Source:
- Created four calculated site columns. Added these four columns into content type. Downloaded source template

Success:
- Provisioned template successfully. Created a list and added provisioned content type. Observed all four calculated columns in the list.
