### ISSUE TITLE
Support for Connected Client Side Web Parts

### ISSUE THREAD

**Issue by jimmywim** [SharePoint/PnP-Sites-Core#2079] opened 2019-02-19 14:25 UTC
#### Category
[ ] Bug
[ * ] Enhancement

#### Environment
[ * ] Office 365 / SharePoint Online
[ * ] SharePoint 2016

Various objects in PnP (including `ClientSideWebPart` and the Provisioning Templates) don't expose the `dynamicDataPaths` and `dynamicDataValues` properties which holds data required for Connected Web Parts

#### Expected or Desired Behavior
`ClientSideWebPart` should expose a member that holds Dynamic Data Paths and Values as dictionaries of dynamic data sources used for Connected Web Parts.

Support a way to write back changes to the dynamic data sources (such as during provisioning time).

You can see the structure of both dynamic data properties when you add connect up some web parts in Workbench then look at the Web Part Data.

[fundamentally, the ModernSearch web parts don't provision using PnP Templates with their saved Connection details. i.e. the Search Results Web Part with it's connection to the Search Box web part]

#### Observed Behavior
dynamicData is available in the raw JSON Web Part Data, but the parser in PNP misses out this property when hydrating its own properties. It is also missing a publicly accessible property to store this info.

Ideally, the `Set-PnPClientSideWebPart` cmdlet allows setting of DynamicDataPaths/Values.

**Comment by jimmywim** [comment] 2019-02-19 18:39
As a hack/workaround I've tried parsing the HTML content of the `CanvasContent1` field of the Page's Item using `HTMLFile` COM Object (I'm in PowerShell), pulling out the `data-sp-webpart` attribute, doing a `ConvertFrom-Json` on the value to get a nice PowerShell object and fudging in the values for `dynamicDataPaths` and `dynamicDataValues`, and setting the field value back in after serializing everything back down - the web part appears to have the connection configured fine but I'm missing something as I get this in the JS console in the browser, every second:

```
Uncaught Error
    at t [as constructor] (sp-pages-assembly_en-gb_ae9aacb7b5c022f3507af32f5ec9ef42.js:879)
    at new t (sp-pages-assembly_en-gb_ae9aacb7b5c022f3507af32f5ec9ef42.js:1836)
    at Function.t.create (sp-pages-assembly_en-gb_ae9aacb7b5c022f3507af32f5ec9ef42.js:1836)
    at t._internalSerialize (sp-pages-assembly_en-gb_ae9aacb7b5c022f3507af32f5ec9ef42.js:1836)
    at t._internalSetDirtyBit (sp-pages-assembly_en-gb_ae9aacb7b5c022f3507af32f5ec9ef42.js:1836)
    at sp-pages-assembly_en-gb_ae9aacb7b5c022f3507af32f5ec9ef42.js:1836
    at sp-pages-assembly_en-gb_ae9aacb7b5c022f3507af32f5ec9ef42.js:1836
    at Map.forEach (<anonymous>)
    at e._executeForIdsOrAll (sp-pages-assembly_en-gb_ae9aacb7b5c022f3507af32f5ec9ef42.js:1836)
    at sp-pages-assembly_en-gb_ae9aacb7b5c022f3507af32f5ec9ef42.js:1836
```

For funsies, here's the (in progress) PowerShell that I'm using to hack the connection values. Note that "Search.aspx" is a PnP Provisioned Page with the Modern Search SearchBox and SearchRefiner web part added, and connected together [I don't yet believe this bug/feature request is specific to ModernSearch however, and a broader issue with serialization of Connection data within PnP].

```
Write-Output "Fixing Search Page"
$page = Get-PnPClientSidePage Search
$searchBox = Get-PnPClientSideComponent -Page Search | ? {$_.Title -eq "Search Box"}
$searchBoxInstanceId = $searchBox.InstanceId

$searchResults = Get-PnPClientSideComponent -Page Search | ? {$_.Title -eq "Search Results with Refiners"}
$searchResultsInstanceId = $searchResults.InstanceId

$props = $searchResults.PropertiesJson | ConvertFrom-Json
$connection = $props.sourceId
$connectionArray = $connection.Split(".")

$oldSearchBoxInstanceId = $connectionArray[2]
$connectionArray[2] = $searchBoxInstanceId
$connection = [string]::Join(".", $connectionArray)
$props.sourceId = $connection

$propsJson = ($props |ConvertTo-Json) -replace "`n|`r"
Set-PnPClientSideWebPart Search -Identity $searchResultsInstanceId -PropertiesJson $propsJson

$file = Get-PnPFile -Url SitePages/Search.aspx
$item = Get-PnPProperty -ClientObject $file -Property ListItemAllFields
$pageContent = $item.FieldValues["CanvasContent1"]
$pageContent = $pageContent.Replace($oldSearchBoxInstanceId, $searchBoxInstanceId.ToString())

$html = New-Object -ComObject "HTMLFile";
$html.IHTMLDocument2_write($pageContent);
$webPartData = $html.all.tags("div")[6].attributes("data-sp-webpartdata").value |ConvertFrom-JSon

$value = $connection + ":searchQuery:Raw user search query"
$dynamicDataPath = @{ queryKeywords = $value}
$serverProcessedContent = @{
  htmlString = @{}
  searchablePlainTexts = @{}
  imageSources = @{}
  links = @{}
}

Add-Member -MemberType NoteProperty -Name dynamicDataPaths -Value $dynamicDataPath -InputObject $webPartData
Add-Member -MemberType NoteProperty -Name dynamicDataValues -Value @{} -InputObject $webPartData
Add-Member -MemberType NoteProperty -Name serverProcessedContent -Value $serverProcessedContent -InputObject $webPartData

$wpDataString = ($webPartData | ConvertTo-Json -Compress -Depth 8) -replace "`n|`r"
$html.all.tags("div")[6].attributes("data-sp-webpartdata").value = $wpDataString

$pageContent = $html.body.firstChild.outerHTML

$pageProperties = @{ CanvasContent1 = $pageContent }
Set-PnPListItem -List SitePages -Identity $item -Values $pageProperties
```

**Comment by YannickRe** [comment] 2019-03-11 19:00
My investigation shows that the dynamicDataPaths property doesn't get exported with Get-PnPProvisioningTemplate (I can only assume that they don't get imported either, if I'd add it manually).

Problem goes a bit deeper, I think. The ModernSearch webparts (https://github.com/SharePoint/sp-dev-solutions/tree/master/solutions/ModernSearch) try to work around some other issue by storing the dynamic property path in their own properties and resolving them on render. With the provisioning it still doesn't work.
Out of the box value:
```
    "dynamicDataPaths": {
      "queryKeywords": "WebPart.096b96cc-8a44-41fa-9b4d-c0ab2ab2a779.4fd483bf-954b-4de8-96e6-7d638cecc1b4:searchQuery:rawInputValue"
    },
```
Search Results Web Part value:
```
      "sourceId": "WebPart.096b96cc-8a44-41fa-9b4d-c0ab2ab2a779.4fd483bf-954b-4de8-96e6-7d638cecc1b4",
      "propertyId": "searchQuery",
      "propertyPath": "rawInputValue",
```

The sourceId value is stored as `WebPart.<Id>.<InstanceId>` and I think this is the root cause. PnP Provisioning creates the web parts correctly, but every execution generates a new InstanceId for each web part and thus breaking the dynamic connection.

Does the API allow provisioning modern webparts with a fixed InstanceId?

**Comment by jansenbe** [comment] 2019-03-29 11:58
Closing this one, @YannickRe has been merged and will be part of the April drop

**Closed by jansenbe** 2019-03-29 11:58 UTC
