### ISSUE TITLE
Provisioning : File not correctly uploaded using the token {sitecollection} on a sub site

### ISSUE THREAD

**Issue by PierreBiname** [SharePoint/PnP-Sites-Core#722] opened 2016-08-26 10:10 UTC
**#### Which PnP repository to report the issue?**
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

**#### Category**
[X ] Bug
[ ] Enhancement

**#### Environment**
[X ] Office 365 / SharePoint Online
[X ] SharePoint 2016
[X ] SharePoint 2013

**#### Expected or Desired Behavior**
I apply a template on a sub site with some files to provision to the style library.
`
<pnp:Files>
     <pnp:File Src="jquery.js" Folder="{sitecollection}/Style Library/Assets/Plugins" Overwrite="true" /></pnp:Files>
`
I excpect that the JS file is uploaded in the style library of the site collection.

**#### Observed Behavior**
Site collection URL :  _http://sharepoint/site/root_
Sub Site URL : _http://sharepoint/site/root/sub_

Regarding the XML sample in the expected behavior if I apply the template to the sub site I expect that the file is uploaded at _http://sharepoint/site/root/sub/site/root/Style Library/Assets/Plugins/jquery.js_.

Normaly it should be uploaded at  _http://sharepoint/site/root/Style Library/Assets/Plugins/jquery.js_

**#### Steps to Reproduce**
- Create a template that provision files to the site collection using the token
- Apply the template to a sub site

**#### Submission Guidelines**
In the file _PnP-Sites-Core/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectFiles.cs_ at the line 52
the code should be something like this : 

```
var webToUpload = web;

 var folderName = tokenParser.ParseString(template.Files.First().Folder);

 if (folderName.ToLower().StartsWith((webToUpload.ServerRelativeUrl.ToLower())))
 {
     folderName = folderName.Substring(webToUpload.ServerRelativeUrl.Length);
 }
 else if (folderName.ToLower().StartsWith((context.Site.RootWeb.ServerRelativeUrl.ToLower())))
 {
     folderName = folderName.Substring(context.Site.RootWeb.ServerRelativeUrl.Length);
     webToUpload = context.Site.RootWeb;
 }

var folder = webToUpload.EnsureFolderPath(folderName);
```

Then use the variable webToUpload in rest of the foreach block.

Regards,

Pierre

**Comment by jansenbe** [comment] 2017-02-06 01:23
One of the design tenets of the engine is that when we provision a sub site we're not changing the root site of the site collection and this bug report is exactly asking that. This is something we've debated about a lot with the PnP team in the past and we decided to not allow this 'sub site updates root site' model. 

Given this is "by design" I'll be closing this issue

**Closed by jansenbe** 2017-02-06 01:23 UTC
