### ISSUE TITLE
Unable to provision a QuickLinks modern web part with content

### ISSUE THREAD

**Issue by wobba** [SharePoint/PnP-Sites-Core#1358] opened 2017-09-22 12:23 UTC
#### Category
[x] Bug

#### Environment
[x] Office 365 / SharePoint Online

#### Expected or Desired Behavior
When saving a template from a modern site which has a QuickLinks web parts on the page with content, and applying the template, I expect the links added to show.

#### Observed Behavior
When applying a template saved with Pages/PageContents handlers, the quick links web part is added, but the links are not rendered - even though they appear to be present in the `JsonControlData`.

#### Steps to Reproduce
Edit for example the home page on a Group team site. Remove all web parts and add a quick links web part. Then add one link and save the page.

Extract a template from the site with `Get-PnPProvisioningTemplate -Out .\home_page.xml -Handlers PageContents,Pages`. Change overwrite from false to true in the template, then run `Apply-PnPProvisioningTemplate -Path .\home_page.xml`.

The page will now be blank. If you edit the page you see the web part, but with no links.

**Comment by chrisobriensp** [comment] 2017-10-02 11:12
I'm also struggling to provision this web part. I've tried several approaches, including:

- setting the JsonControlData to a value obtained from an existing, configured control on the page (also tried various flavours of cleaning this up)
- using both PnP XML and the PnP ClientSidePage API to set JsonControlData
- attempting to set Properties rather than PropertiesJson

No joy so far. Any ideas at all @jansenbe?

Thanks for any help :)

**Comment by DariuS231** [comment] 2017-10-02 15:55
I created a new solutions and was able to provision a new Modern Page with Quick Links web parts. Here is the template I used: 
``` XML
<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2017/05/ProvisioningSchema">
  <pnp:Preferences  Version="1.0" >
    <pnp:Parameters>
      <pnp:Parameter Key="lcid">1033</pnp:Parameter>
    </pnp:Parameters>
  </pnp:Preferences>
  <pnp:Templates ID="CONTAINER-TEMPLATE">
    <pnp:ProvisioningTemplate ID="TEMPLATE">
      <pnp:ClientSidePages>
        <pnp:ClientSidePage PageName="Home.aspx" PromoteAsNewsArticle="false" Overwrite="true">
          <pnp:Sections>
            <pnp:Section Order="1" Type="OneColumn">
              <pnp:Controls>
                <pnp:CanvasControl WebPartType="QuickLinks" JsonControlData="{&quot;items&quot;:[],&quot;isMigrated&quot;:true,&quot;layoutId&quot;:&quot;CompactCard&quot;,&quot;shouldShowThumbnail&quot;:true,&quot;hideWebPartWhenEmpty&quot;:true,&quot;dataProviderId&quot;:&quot;QuickLinks&quot;,&quot;webId&quot;:&quot;5a8ae54c-f7ec-48f2-8380-ceb0bba2728b&quot;,&quot;siteId&quot;:&quot;3c3973bd-dcd3-44bf-83e3-ff50caee41a5&quot;,&quot;baseUrl&quot;:&quot;https://google.com&quot;,&quot;title&quot;:&quot;&quot;}" ControlId="c70391ea-0b10-4ee9-b2b4-006d3fcad0cd" Column="1" />
                <pnp:CanvasControl WebPartType="QuickLinks" JsonControlData="{&quot;items&quot;:[{&quot;id&quot;:-1,&quot;itemType&quot;:2,&quot;siteId&quot;:&quot;&quot;,&quot;webId&quot;:&quot;&quot;,&quot;uniqueId&quot;:&quot;&quot;,&quot;fileExtension&quot;:&quot;&quot;,&quot;progId&quot;:&quot;&quot;,&quot;activity&quot;:{&quot;activity&quot;:&quot;Added a few seconds ago&quot;,&quot;people&quot;:[{&quot;name&quot;:&quot;SharePoint&quot;,&quot;profileImageSrc&quot;:&quot;https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-09-08.040/icon_sp-icon_fd9ed950.png&quot;,&quot;initials&quot;:&quot;&quot;}]},&quot;hasInvalidUrl&quot;:false,&quot;flags&quot;:1,&quot;renderInfo&quot;:{&quot;imageUrl&quot;:&quot;https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-09-08.040/icon_quicklinksdefault2x_46e83f7a.png&quot;,&quot;compactImageInfo&quot;:{&quot;iconName&quot;:&quot;Globe&quot;,&quot;color&quot;:&quot;&quot;,&quot;imageUrl&quot;:&quot;&quot;,&quot;forceIconSize&quot;:true},&quot;backupImageUrl&quot;:&quot;https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-09-08.040/icon_link_22d1503c.png&quot;,&quot;iconUrl&quot;:&quot;&quot;,&quot;accentColor&quot;:&quot;&quot;,&quot;imageFit&quot;:2,&quot;forceStandardImageSize&quot;:false}}],&quot;isMigrated&quot;:true,&quot;layoutId&quot;:&quot;FilmStrip&quot;,&quot;shouldShowThumbnail&quot;:true,&quot;dataProviderId&quot;:&quot;QuickLinks&quot;,&quot;webId&quot;:&quot;5a8ae54c-f7ec-48f2-8380-ceb0bba2728b&quot;,&quot;siteId&quot;:&quot;3c3973bd-dcd3-44bf-83e3-ff50caee41a5&quot;,&quot;baseUrl&quot;:&quot;https://google.com&quot;,&quot;hideWebPartWhenEmpty&quot;:true,&quot;title&quot;:&quot;&quot;}" ControlId="c70391ea-0b10-4ee9-b2b4-006d3fcad0cd" Column="1" />
              </pnp:Controls>
            </pnp:Section>
          </pnp:Sections>
        </pnp:ClientSidePage>
      </pnp:ClientSidePages>
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>
```

**Comment by jansenbe** [comment] 2017-10-05 08:13
Seems like the web part is not storing the actual links in it's JSON properties...will need to investigate this one.

**Comment by LudwigVanGysel** [comment] 2017-10-05 09:38
I would like this too so I can provision a web part with predefined links using CSOM. The properties are indeed not stored in the "Properties" but in the "WebPartData" which has only a getter and not a setter.

**Comment by zplume** [comment] 2017-10-13 20:04
Hi,

Same issue here.

I *almost* got this working, but not quite.

If I add a Quick Links web part to a modern page via CSOM and then edit and save the page via the UI, I can programmatically add items to the Quick Links web part and these show up on the page (note that the solution requires using reflection to update the private htmlPropertiesData property on the quick links ClientSideWebPart instance - code and details here: https://gist.github.com/zplume/ca292d0f03451b285753e681514d182c).

Unfortunately editing pages via the UI is not a workable solution.
I need to automate page updates for several thousand site collections.

If I don't edit and save the page via the UI after adding the Quick Links web part, subsequent attempts to add items to the Quick Links web part via code will fail silently.

Is there something happening in the API call to "/_api/sitepages/pages(86)/SavePage" that is triggered by saving the page from the UI that we need to replicate in our code (preferably without replicating that POST request)?

Thanks

**Comment by zplume** [comment] 2018-01-04 22:08
Thanks to some clues here...
https://www.youtube.com/watch?v=axgAhVkWb34

...and picking through the updated OfficeDev PnP code here...
https://github.com/SharePoint/PnP-Sites-Core/blob/62d3a007ea4f52d4715ce57928928ebe0e0b06b7/Core/OfficeDevPnP.Core/Pages/ClientSidePageControls.cs

...I've finally got this working!

I've updated my example code:
https://gist.github.com/zplume/ca292d0f03451b285753e681514d182c

Thanks!

**Comment by jansenbe** [comment] 2018-01-05 09:08
Nice one, thanks for sharing. To further improve the experience one of the things I've been considering is creating classes per web part (e.g. a QuickLinksWebPart or ImageWebPart) inheriting from the ClientSideWebPart class and in there one could add logic that will generate the needed JSON. So adding a method "AddImage" to the web part would then generate the correct JSON (or even upload the image if needed). Obviously a lot of work and still requires some thinking, but wanted to check your thoughts on this?

**Comment by zplume** [comment] 2018-01-05 10:44
@jansenbe that would be a great help!

Thanks again

**Comment by tomjan7** [comment] 2018-01-09 15:48
I have successfully used it to add quick links with layoutId = "FilmStrip"
When I try to use it with layoutId = "CompactCard" I am not able to make the link icon appear (apart from that it works). 
It seems that in this case the CompactImageInfo should contain more information. I tried specyfying imageUrl inside compactImageInfo but it is still not rendering the image
Do you have a working sample with layoutId = "CompactCard"?

**Comment by ndl7** [comment] 2018-04-27 09:00
Did anyone had any luck creating a new Quick Links web part with PnP PowerShell (Add-PnPClientSideWebPart)?

**Comment by jansenbe** [comment] 2018-04-27 09:39
The page API does support adding quick link web part, it's a matter of correctly defining the json properties. Would recommend configuring the web part in workbench and then copy the json properties from there. Since PnP PS is simply calling the page API this should work as well.

**Comment by robbert-vanandel** [comment] 2018-06-29 20:05
I too am unable to add the web part.  I've done all manner of combination of properties, including using the full set of properties.

First try

    $options = @{
            "items"=@(
                @{"sourceItem"=@{"url"="https://teams.microsoft.com";"itemType"=2;"fileExtension"="";"progId"=""};"thumbnailType"=3;"id"=2},
                @{"sourceItem"=@{"url"="https://mytenant.sharepoint.com/sites/eng";"itemType"=2;"fileExtension"="";"progId"=""};"thumbnailType"=3;"id"=1}
            );
            "isMigrated"=$true;
            "layoutId"="CompactCard";
            "shouldShowThumbnail"=$true;
            "deprecatedItems"=@();
            "hideWebPartWhenEmpty"=$true;
            "dataProviderId"="QuickLinks";
            "webId"=$web.Id;
        }

That didn't work. I just puts two blank links on the quick links that eventually end up on the page.  I've gradually added more and of the web part's properties from the site's workbench, to no avail. 

The last attempt

    $options =  @{
       "controlType" = 3;
       "displayMode" = 2;
       "id" = "0fd2d4fb-556f-4167-860c-0ac5f8022c6a";
       "webPartId" = "c70391ea-0b10-4ee9-b2b4-006d3fcad0cd";
       "webPartData" = @{
          "id" = "c70391ea-0b10-4ee9-b2b4-006d3fcad0cd";
          "instanceId" = "0fd2d4fb-556f-4167-860c-0ac5f8022c6a";
          "title" = "Quick links";
          "description" = "Add links to important documents and pages.";
          "serverProcessedContent" = @{
             "htmlStrings" = @{ };
             "searchablePlainTexts" = @{
                "title" = "";
                "items[0].title" = "Teams";
                "items[1].title" = "Site";
                "items[0].description" = "";
                "items[1].description" = "";
                "items[0].altText" = "";
                "items[1].altText" = "";
             };
             "imageSources" = @{
                "items[1].rawPreviewImageUrl" = "/_layouts/15/images/siteIcon.png";
             };
             "links" = @{
                "baseUrl" = "https = //mytenant.sharepoint.com/sites/WebPartTest2";
             };
             "componentDependencies" = @{
                "layoutComponentId" = "706e33c8-af37-4e7b-9d22-6e5694d92a6f";
             };
          };
          "dataVersion" = "2.0";
          "properties" = @{
             "items" = @(
                @{
                   "sourceItem" = @{
                      "url" = "https = //teams.microsoft.com";
                      "itemType" = 2;
                      "fileExtension" = "";
                      "progId" = "";
                   };
                   "thumbnailType" = 3;
                   "id" = 2;
                };
                @{
                   "sourceItem" = @{
                      "url" = "https = //mytenant.sharepoint.com/sites/eng";
                      "itemType" = 2;
                      "fileExtension" = "";
                      "progId" = "";
                   };
                   "thumbnailType" = 3;
                   "id" = 1;
                }
             );
             "isMigrated" = $true;
             "layoutId" = "CompactCard";
             "shouldShowThumbnail" = $true;
             "deprecatedItems" = @();
             "hideWebPartWhenEmpty" = $true;
             "dataProviderId" = "QuickLinks";
             "webId" = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx";
             "siteId" = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx";
          }
       }
    };
    @{
       "displayMode" = 2;     
    }

This last attempt leaves me with an empty Quick Links web part with a message Nothing to show here.

**Comment by jansenbe** [comment] 2018-07-13 15:05
Yesterday I fixed an issue around dataVersion handling: essentially in my scenario an extracted page with quicklinks did not result in an working quicklinks after being applied to another site. Root cause was that the pages API was not correctly handling the dataversion and wrongly used version 1.0 while the quicklinks data model currently is at version 2.0. With this change I was able to export/import quicklinks web parts without an issue...so would recommend checking the current dev build to see if that fixes things for you.

**Comment by jansenbe** [comment] 2018-09-13 10:02
Nothing really changed and quicklinks, like any other web part, has been working fine. The key thing to remember is to take *all* web part properties when you configure your quicklinks web part. What I typically do is configure it via WorkBench, take the full properties JSON and then ensure that needed guids and urls are replaced with the values for my target site. WHen you leave these fields empty or assume that the webpart will "complete" the data then often that's not the case.

**Comment by jansenbe** [comment] 2019-03-29 12:16
Closing this issue...feel free to re-open if you still feel this is blocking you.

**Closed by jansenbe** 2019-03-29 12:16 UTC
