### ISSUE TITLE
 Remove content type binding from a list issue

### ISSUE THREAD

**Issue by konraplo** [SharePoint/PnP-Sites-Core#799] opened 2016-10-13 09:52 UTC
Hi
I try to remove content type binding from list using attribute ‘Remove="true"’ in contenTypeBinding. If this content type is in use – I have got an exception. 

Which PnP repository to report the issue?
• PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core Master Branch 

Category
[ x] Bug
[ ] Enhancement

Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[x ] SharePoint 2013

Expected or Desired Behavior
If content type is in use in that list, content type binding remains in the list.

Observed Behavior
If content type is in use in that list – throw exception by provisioning.

Steps to Reproduce
Provision template with pnp:ContentTypeBinding containing parameter Remove="true".

**Comment by jansenbe** [comment] 2017-02-06 03:21
This is by design, you'll first need to delete all references to that content type. Since the engine will not delete data (that's the choice we made) we're not able to fix this and as such will close the issue.

**Closed by jansenbe** 2017-02-06 03:21 UTC
