### ISSUE TITLE
Apply-PnPProvisioningTemplate : The requested operation is part of an experimental feature that is not supported in the current environment.

### ISSUE THREAD

**Issue by UMAknow-Kien** [SharePoint/PnP-Sites-Core#1747] opened 2018-05-08 20:55 UTC
#### Category
[ X ] Bug
[ ] Enhancement

#### Environment
[ X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Apply the blank provisioning template without error.

#### Observed Behavior
A PowerShell error when running Apply-PnPProvisioningTemplate.

"Apply-PnPProvisioningTemplate : The requested operation is part of an experimental feature that is not supported in the current environment."

#### Steps to Reproduce
1. Create a blank communication site (modern)
2. Install the latest PnP PowerShell (2.26.1805.0)
3. Connect to the newly created site using Connect-PnPOnline
4. Run Get-PnPProvisioningTemplate -Out template.xml
5. Run Apply-PnPProvisioningTemplate -Path .\template.xml

Get the error above.

Here is the template:

<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2018/05/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.26.1805.0, Culture=neutral, PublicKeyToken=5e633289e95c321a" />
  <pnp:Templates ID="CONTAINER-TEMPLATE-DAD8019E64034520916E3924BDE10D5B">
    <pnp:ProvisioningTemplate ID="TEMPLATE-DAD8019E64034520916E3924BDE10D5B" Version="1" BaseSiteTemplate="SITEPAGEPUBLISHING#0" Scope="RootSite">
      <pnp:RegionalSettings AdjustHijriDays="0" AlternateCalendarType="None" CalendarType="Gregorian" Collation="25" FirstDayOfWeek="Sunday" FirstWeekOfYear="0" LocaleId="1033" ShowWeeks="false" Time24="false" TimeZone="13" WorkDayEndHour="5:00PM" WorkDays="62" WorkDayStartHour="8:00AM" />
      <pnp:PropertyBagEntries>
        <pnp:PropertyBagEntry Key="SiteCollectionGroupId65530472-06dc-4419-8566-0c903ca2ff5a" Value="c3598893-a724-4a6f-8a60-d1be40fb4893" Overwrite="false" />
      </pnp:PropertyBagEntries>
      <pnp:Security>
        <pnp:AdditionalAdministrators>
          <pnp:User Name="i:0#.f|membership|user@tenant.onmicrosoft.com" />
        </pnp:AdditionalAdministrators>
        <pnp:AdditionalOwners>
          <pnp:User Name="i:0#.f|membership|user@tenant.onmicrosoft.com" />
        </pnp:AdditionalOwners>
        <pnp:Permissions />
      </pnp:Security>
      <pnp:Features>
        <pnp:WebFeatures>
          <pnp:Feature ID="d5a4ed08-27b9-4142-9804-45dec6fda126" />
          <pnp:Feature ID="e233eb34-e720-4ff9-9f53-a5aabc706d12" />
        </pnp:WebFeatures>
      </pnp:Features>
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>

![capture](https://user-images.githubusercontent.com/19476512/39782527-727fdf16-52e0-11e8-81b4-7c243b262ee2.PNG)

**Comment by erwinvanhunen** [comment] 2018-05-08 21:39
Hi!

Unfortunately I'm not able to reproduce the issue you describe. Following the sequence of cmdlets you post in your screenshot succeeds for me without a problem. 

I even took the template (some copy pasting errors I assume as some of the tags where missing) you posted and applied that succesfully to a site I just created.

Can you try to reproduce the error and then straight after that enter:

```powershell
$error[0].Exception.Stacktrace
```

This will output the full stacktrace of where the error occured. Please post that stacktrace here so we can dive a bit deeper into what's going on on your end.

Regards,

/Erwin

**Comment by UMAknow-Kien** [comment] 2018-05-09 11:54
![image](https://user-images.githubusercontent.com/19476512/39813368-305f393c-535e-11e8-9921-8f60e856394a.png)

**Comment by UMAknow-Kien** [comment] 2018-05-09 11:56
![image](https://user-images.githubusercontent.com/19476512/39813432-7106b136-535e-11e8-85eb-3ec9bc0a150d.png)
 
Copy pasting in Git Hub removed some tags. Here is the entire template (screenshot).

**Comment by UMAknow-Kien** [comment] 2018-05-09 12:15
I would also like to bring to your attention that:
- downgrading to version 2.25.1804.1 works and completes the cmdlet without error;
- the tenant I'm running the cmdlet against is in Targeted Release

**Comment by erwinvanhunen** [comment] 2018-05-10 21:55
Thank you for this. I think I see where it goes wrong when looking at the code. I'll work on a fix.

**Comment by erwinvanhunen** [comment] 2018-05-10 21:59
Just for my confirmation: I assume you are not running the engine with an account that has tenant administration rights?

**Comment by erwinvanhunen** [comment] 2018-05-10 23:09
A fix for this issue has been merged through PR #1752

**Closed** 2018-05-10 23:09 UTC
Labels: To be processed, enhancement

**Comment by UMAknow-Kien** [comment] 2018-05-11 13:58
Yes, my account happens to be tenant admin as well.

**Comment by erwinvanhunen** [comment] 2018-05-11 14:49
Interesting. Effectively was what was happening is that the engine would create a context towards the tenant administration site in order process any outstanding webapi approval requests. However, in your template where no such approvals defined. It nevertheless still builds a context towards the tenant admin site. And if you're not tenant admin, that's where it goes wrong. But in your case you are tenant admin, so that's puzzling.

**Comment by asestromsrud** [comment] 2020-06-04 06:53
@erwinvanhunen 
You need to look into newer versions because the error has come back. We have had a lot of trouble with this function. Tried to get it work in Runbook in azure with several versions. Luckily I had an older version locally that worked and when I tested to load that in the Automation account it worked. The version I got to work is: 
3.13.1909.0
The latest in Azure didn't work. Neither 3.19.2003.0.

**Comment by JonvR** [comment] 2020-09-02 11:06
@erwinvanhunen 
So I also have this problem, at first I got a message about a push notification not being enabled, for which the fix is to enable a feature **Enable-PnPFeature -Identity '41e1d4bf-b1a2-47f7-ab80-d5d6cbba3092'** 
then I ran into this issue regarding the experimental problem. I'm running 3.24.2008.1 from an azure runbook. 
The fix for me was that it only affected the first statement and that in disregards in what the statement does. 
I'm using the returnconnection on a site and my account is not a tenant admin, just a SharePoint Admin. I'm using an appID and secret to connect to the sites.
But this works:
Enable-PnPFeature -Identity '41e1d4bf-b1a2-47f7-ab80-d5d6cbba3092' -Connection $connectionSite
Apply-PnPProvisioningTemplate <URL to pnp file> -Connection $connectionSite

It will fail on the first statement, but succesfully implement the Apply statement. If I just do the apply statement it will fail. It doesn't matter what the first statement is as long as it does something with the site. So a get doesn't do it. 
So the workaround for me is to just do this with the first command
Enable-PnPFeature -Identity '41e1d4bf-b1a2-47f7-ab80-d5d6cbba3092' -Connection $connectionSite -ErrorAction Ignore
