### ISSUE TITLE
Exporting/Importing termsets fails

### ISSUE THREAD

**Issue by PieterVeenstra** [SharePoint/PnP-Sites-Core#428] opened 2016-02-29 12:18 UTC
Whenever a term contains a '&' the import fails with the following error:

Apply-SPOProvisioningTemplate : An error occurred while parsing EntityName. Line 7712, position 57.

An example of a term going wrong:

<pnp:Term Name="Health, Safety ＆ Environment" ID="a195076e-976a-45a0-ad11-6ae848883a60" CustomSortOrder="10" /> 

replacing the & with "& a m p ;" in the template.xml fixes the issue on the import.

**Comment by PaoloPia** [comment] 2016-12-08 10:13
Hi Pieter,
That's a very good catch. Digging into this issue, it looks like the & character is not represented as 0x26 (which would have to be encoded as &amp; in XML) but as 0xEF (which does not require encoding from an XML perspective). However, I cannot reproduce the issue and I have a bunch of customers using the & character in their taxonomies. Thus the question is: are you still experiencing this issue? Thanks.

**Comment by PaoloPia** [comment] 2017-01-04 14:33
Hi Pieter,
Let me try to close this item in the meantime. If you will still experience the issue, feel free to re-open it. Thanks a lot.

**Closed by PaoloPia** 2017-01-04 14:33 UTC
