### ISSUE TITLE
Missing WF in [Get/Apply]-PnPProvisioningTemplate process

### ISSUE THREAD

**Issue by abelunibo** [SharePoint/PnP-Sites-Core#1001] opened 2017-01-25 15:24 UTC
#### Category
[ ] Bug
[x] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[x] SharePoint 2016
[x] SharePoint 2013

#### Expected or Desired Behavior
When I export a site as a template it does not include information about existing workflows. 

#### Observed Behavior
Major artifacts are exported/applied but workflows are missing

#### Steps to Reproduce
Simply export a normal site with a list with workflows it could be either an oob workflow or a workflow created with spd. I have tested this with 2010 WF,  but my guess is that for 2013 WF there will be the same.

**Comment by jansenbe** [comment] 2017-02-03 12:15
Hi Abel,

The engine today is not supporting 2010 WF, only 2013 WF is exported/imported. We're open for accepting a PR from the community that brings 2010 WF handling, but for now we're closing this issue as the behavior you see is "by design".

**Closed by jansenbe** 2017-02-03 12:15 UTC
