### ISSUE TITLE
If Documents Library Already exists - then Apply-SPOProvisioningTemplate Fails

### ISSUE THREAD

**Issue by NPrice99** [SharePoint/PnP-Sites-Core#394] opened 2016-02-18 11:31 UTC
Hi

If I create a new site (or subsite) using the Team template. It creates a document library called "Documents".  When you run Apply-SPOProvisioningTemplate it fails because "Documents" is already there (The template was created from an existing site)  :-

PS C:\WINDOWS\system32> Apply-SPOProvisioningTemplate

cmdlet Apply-SPOProvisioningTemplate at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
Path: C:\Users\Nigel\Documents\Visual Studio 2015\Projects\CSOM\provisioningtemplate01112015_4.xml
Apply-SPOProvisioningTemplate : A list, survey, discussion board, or document library with the specified title already
exists in this Web site.  Please choose another title.
At line:1 char:1
- Apply-SPOProvisioningTemplate
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : WriteError: (:) [Apply-SPOProvisioningTemplate], ServerException
  - FullyQualifiedErrorId : EXCEPTION,OfficeDevPnP.PowerShell.Commands.Branding.ApplyProvisioningTemplate

Should the Provisioning Template just Ignore the "Documents" library ?

Regards

Nigel

**Comment by PaoloPia** [comment] 2016-02-21 10:02
Hi Nigel, 
could you please share the failing template? So that we can investigate the happening.
Thanks.

**Comment by NPrice99** [comment] 2016-02-21 15:25
Hi Paolo
Enclose provisioning template as requested.
This is my test provisioning template so will also show problem with lookup fields and on-premises farms where list to be looked up is blank.


Regards

Nigel

[provisioningtemplate01112015_4.zip](https://github.com/OfficeDev/PnP-Sites-Core/files/139675/provisioningtemplate01112015_4.zip)

**Comment by PaoloPia** [comment] 2016-02-22 00:35
Ok, I've got the file, but I cannot reproduce the issue on my side.

BTW, we cannot ignore that "Documents" list instance, because during delta handling we handle any delta, and moreover in your template the "Documents" library is not the standard (STS#0) one. There are a couple of custom fields, which are custom.

What is the site base template from which you generated the template, and what is the site base template of the target site (on which you apply this template)? What are the relative URLs of the source and target site? Are you on-prem? Thanks.

**Comment by PaoloPia** [comment] 2016-12-07 23:56
Hi Nigel,
Any feedback about this topic? Or we can close it? Thanks.

**Comment by cheindel** [comment] 2016-12-16 00:56
Hello @NPrice99,

Could you please execute `Get-Culture` in the PowerShell context where you execute Apply-PnPProvisioningTemplate and check if the culture being returned matches the supported culture of your template (1033)?

I've noticed problems when the wrong culture is set for the PowerShell session. If that's the case for you, you might be able to work around by using `Set-Culture -CultureInfo en-us` before applying the template.

**Comment by PaoloPia** [comment] 2017-01-04 11:27
Hi Nigel,
Any progress on this item? Can we close it? Thanks.

**Comment by PaoloPia** [comment] 2017-01-11 17:53
Hi Nigel,
I don't see any answer. In the meantime I will close this issue. Feel free to drop me a message if you have any new feedback and I will be more than happy to re-open it and support you. Thank you.

**Closed by PaoloPia** 2017-01-11 17:53 UTC
