### ISSUE TITLE
[BUG] Provisioning Timeline Webpart fails

### ISSUE THREAD

**Issue by stact** [SharePoint/PnP-Sites-Core#563] opened 2016-05-20 09:00 UTC
#### Category

[x] Bug
[ ] Enhancement
#### Environment

[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[x] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 15.0.4763.1000 (October 2015 CU)
#### Expected or Desired Behavior

Using PnP remote provisioning schema, insert Timeline webpart on a specific page
#### Observed Behavior

When the provisioning ended, we refresh the specific page and An unexpected error occurred:

`
System.FormatException: Expected hex 0x in '{0}'.
 at System.Guid.GuidResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument, String failureArgumentName, Exception innerException)    
 at System.Guid.TryParseGuidWithHexPrefix(String guidString, GuidResult& result)    
 at System.Guid.TryParseGuid(String g, GuidStyles flags, GuidResult& result)    
 at System.Guid..ctor(String g)    
 at Microsoft.SharePoint.WebPartPages.SPTimelineWebPart.GetList(String ListId)    
 at Microsoft.SharePoint.WebPartPages.SPTimelineWebPart.InitializeCtx()    
 at Microsoft.SharePoint.WebPartPages.SPTimelineWebPart.OnPreRender(EventArgs e)    
 at System.Web.UI.Control.PreRenderRecursiveInternal()    
 at System.Web.UI.Control.PreRenderRecursiveInternal()    
 at System.Web.UI.Control.PreRenderRecursiveInternal()    
 at System.Web.UI.Control.PreRenderRecursiveInternal()    
 at System.Web.UI.Control.PreRenderRecursiveInternal()    
 at System.Web.UI.Control.PreRenderRecursiveInternal()    
 at System.Web.UI.Control.PreRenderRecursiveInternal()    
 at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
`
#### Steps to Reproduce

1 - Create a task list named "Roadmap"
2 - Create a "template.xml" for using the pnp provisioning schema
Details : 
https://github.com/OfficeDev/PnP-Provisioning-Schema
https://github.com/OfficeDev/PnP-Provisioning-Schema/blob/master/ProvisioningSchema-2016-05.md
Full sample:
https://github.com/OfficeDev/PnP-Provisioning-Schema/blob/master/Samples/ProvisioningSchema-2016-05-FullSample-02.xml

3 - Insert this following section (care about http://dev, replace with your environment)

``` xml
<pnp:Files>
  <pnp:File Src="Files\Home.aspx" Folder="SitePages" Overwrite="true">
    <pnp:WebParts>
      <!-- ### Roadmap -->
      <pnp:WebPart Title="{resource:WebPart.Home.Roadmap}" Zone="Top" Order="0">
        <pnp:Contents>
          <webParts>
            <webPart xmlns="http://schemas.microsoft.com/WebPart/v3">
              <metaData>
                <type name="Microsoft.SharePoint.WebPartPages.SPTimelineWebPart, Microsoft.SharePoint, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" />
                <importErrorMessage>Cannot import this Web Part.</importErrorMessage>
              </metaData>
              <data>
                <properties>
                  <property name="HelpUrl" type="string" />
                  <property name="ChromeType" type="chrometype">Default</property>
                  <property name="TitleUrl" type="string" />
                  <property name="Width" type="string" />
                  <property name="Hidden" type="bool">False</property>
                  <property name="SourceSelection" type="string">{listid:Roadmap}</property>
                  <property name="AllowClose" type="bool">True</property>
                  <property name="ExportMode" type="exportmode">All</property>
                  <property name="AllowMinimize" type="bool">True</property>
                  <property name="TypeSelection" type="string">TaskListTimeline</property>
                  <property name="Direction" type="direction">NotSet</property>
                  <property name="AllowConnect" type="bool">True</property>
                  <property name="MissingAssembly" type="string">Cannot import this Web Part.</property>
                  <property name="CurrentTaskListWebAddress" type="string">http://dev/</property>
                  <property name="PageAddress" type="string">http://dev/_vti_bin/exportwp.aspx</property>
                  <property name="Description" type="string" />
                  <property name="TitleIconImageUrl" type="string" />
                  <property name="CatalogIconImageUrl" type="string" />
                  <property name="ListId" type="string">{listid:Roadmap}</property>
                  <property name="AllowZoneChange" type="bool">True</property>
                  <property name="Height" type="string" />
                  <property name="ViewName" type="string">Timeline</property>
                  <property name="HelpMode" type="helpmode">Modeless</property>
                  <property name="Title" type="string">{resource:WebPart.Home.Roadmap}</property>
                  <property name="ChromeState" type="chromestate">Normal</property>
                  <property name="AllowHide" type="bool">True</property>
                  <property name="TimelineType" type="string">TaskListTimeline</property>
                  <property name="AllowEdit" type="bool">True</property>
                </properties>
              </data>
            </webPart>
          </webParts>
        </pnp:Contents>
      </pnp:WebPart>
    </pnp:WebParts>
  </pnp:File>
</pnp:Files>
```

4 - Provision your schema.xml throw PowerShell or C# app console
5 - Refresh the specific page
6 - The page display : "An unexpected error has occurred"
#### Submission Guidelines

The Provisioning is working fine for others Webparts.
When we re-run the command, all is fine, but we must run the command twice to have the expected behavior.

Thanks for your contribution!

**Comment by stact** [comment] 2016-05-24 15:07
Let me know if you need any further information.

**Comment by jansenbe** [comment] 2017-02-03 05:41
Internal testing feedback:

Source:
- Followed the steps as specified by the user.

Success: 
- Provisioned roadmap web part successfully in first run itself.

Since the exact same scenario is working I'm assuming the issue is fixed in latest engine release hence I'm closing the issue

**Closed by jansenbe** 2017-02-03 05:41 UTC
Labels: Investigation needed

**Comment by stact** [comment] 2017-02-03 08:29
Thank you Jansenbe! I will try and give you feedback :)
