### ISSUE TITLE
Web-parts not being captured in Provisioning Template

### ISSUE THREAD

**Issue by aaronbonser** [SharePoint/PnP-Sites-Core#851] opened 2016-11-23 06:33 UTC
Issue:
The webparts added in the home page are not captured when doing the Get-SPOProvisioningTemplate and Apply-SPOProvisioningTemplate
 
PnP repository: 
May release 2.4.1605.0
 
Category:
Bug
 
Environment:
Office 365 / SharePoint Online
 
Expected Behaviour:
The site must be created with the webparts in place
 
Steps to Reproduce:
1. Create a SPO site with some webparts
2. Extract the template using Get-SPOProvisioningTemplate
3. Create a provisioning job using Apply-SPOProvisioningTemplate
4. The site created doesn’t have the webparts in it.
 
In the site base xml which is generated after running the command Get-SPOProvisioningTemplate the web parts are commented out for some reason.

![image](https://cloud.githubusercontent.com/assets/23650063/20552828/b96b94f0-b189-11e6-8ca0-a02dc8604b7c.png)

![image](https://cloud.githubusercontent.com/assets/23650063/20552834/cb050106-b189-11e6-8130-524a83e5a731.png)

**Comment by jansenbe** [comment] 2017-02-10 03:01
Hi @aaronbonser ,

You're using a fairly old version of the engine...a lot of improvements have been added in the meanwhile. Can you try to reproduce your issue with the latest version of the engine?

**Comment by jansenbe** [comment] 2017-03-10 10:27
Closing this issue since we've not received feedback for a long time. We want to further investigate this, but if there's no feedback we can't. Absolutely fine for you to re-open the issue if you can still re-produce using the March 2017 release or if you have additional context that can help.

**Closed by jansenbe** 2017-03-10 10:27 UTC
Labels: waiting-for-clarification
