### ISSUE TITLE
Likes fields in list provisioning

### ISSUE THREAD

**Issue by pariom** [SharePoint/PnP-Sites-Core#755] opened 2016-09-14 12:55 UTC
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use PnP Yammer group at http://aka.ms/OfficeDevPnPYammer. Thanks!
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
#### Category

[*] Bug
#### Environment

[ \* ] Office 365 / SharePoint Online
[ \* ] SharePoint 2016
[ \* ] SharePoint 2013

When you provisioning lists, that have active "likes" and use field of likes count? it fails at views creating.

**Comment by jansenbe** [comment] 2017-02-06 01:32
Hi @pariom,

We tried to repro but did not succeed. Can you specify the environment in which you got this error and also if possible share the template you've been using. If the issue is gone in the latest release then please close the issue.

**Comment by jansenbe** [comment] 2017-03-10 10:23
Closing this issue since we've not received feedback for a long time. We want to further investigate this, but if there's no feedback we can't. Absolutely fine for you to re-open the issue if you can still re-produce using the March 2017 release or if you have additional context that can help.

**Closed by jansenbe** 2017-03-10 10:23 UTC
Labels: waiting-for-clarification
