### ISSUE TITLE
GetProvisioningTemplate - Project Site - NullReferenceException

### ISSUE THREAD

**Issue by apadev** [SharePoint/PnP-Sites-Core#1350] opened 2017-09-20 14:51 UTC
Null reference exception thrown when trying to export project site from SharePoint Online using version : 2.18.1709 of SharePointPnPCoreOnline

#### Category
[X ] Bug
[ ] Enhancement

#### Environment
[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
- Export template from Project site
- Get the exported template .pnp as expected

#### Observed Behavior
- Created a new Project site collection. No modification in the site collection
- Trying to export template using a console application
- NullReferenceException thrown at Client Side Page Contents

#### Steps to Reproduce
- Create a new site collection with template type : Project Site
- Trying to export template using this code in a Console Application
```          
 using (var context = new ClientContext(sourceUrl))
            {
                ProvisioningTemplateCreationInformation ptci = new ProvisioningTemplateCreationInformation(web);

                var fileSystemConnector = new FileSystemConnector($@"{AppDomain.CurrentDomain.BaseDirectory}\..\..\Templates", "");

                ptci.FileConnector = new OpenXMLConnector("projectsiteTemplate.pnp", fileSystemConnector);
                ptci.PersistBrandingFiles = true;
                ptci.ProgressDelegate = delegate(string message, Int32 progress, Int32 total)
                {
                    Console.WriteLine("{0:00}/{1:00} - {2}", progress, total, message);
                };

                ProvisioningTemplate template = web.GetProvisioningTemplate(ptci);
                XMLTemplateProvider provider = new XMLOpenXMLTemplateProvider(ptci.FileConnector as OpenXMLConnector);

                provider.SaveAs(template, "projectsiteTemplate.xml");
            }
```

- Here are the steps :
01/16 - Regional Settings
02/16 - Supported UI Languages
03/16 - Audit Settings
04/16 - Site Security
05/16 - Fields
06/16 - Content Types
07/16 - List instances
08/16 - Features
09/16 - Composed Looks
10/16 - Page Contents
11/16 - Client Side Page Contents

The last one throws a NullReferenceException (Object reference not set to an instance of an object)
Stack Trace:
at OfficeDevPnP.Core.Pages.ClientSidePage.Load(ClientContext cc, String pageName)
   at Microsoft.SharePoint.Client.PageExtensions.LoadClientSidePage(Web web, String pageName)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectClientSidePageContents.ExtractObjects(Web web, ProvisioningTemplate template, ProvisioningTemplateCreationInformation creationInfo)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.GetRemoteTemplate(Web web, ProvisioningTemplateCreationInformation creationInfo)
   at Microsoft.SharePoint.Client.WebExtensions.GetProvisioningTemplate(Web web, ProvisioningTemplateCreationInformation creationInfo)
   at PnpProvisioningDemo.Program.Main(String[] args)

**Comment by mkacena** [comment] 2017-09-26 11:01
Same issue here with **Enterprise Wiki** site.

I found out that the problem is caused by the engine assuming that the _Pages_ library has URL of **SitePages**. However, such a library is missing in the site.

**Comment by ebreuker** [comment] 2017-09-28 12:43
I have the same problem at 11/16 - Client Side Page Contents. How can this be resolved?

**Comment by jansenbe** [comment] 2017-09-28 18:44
A fix has been submitted to the dev branch and will appear in the October version. For now, you can omit the clientsidepagecontent handler when extracting sites as that's the one causing the issue. Closing the issue now.

**Closed by jansenbe** 2017-09-28 18:44 UTC
