### ISSUE TITLE
Value cannot be null

### ISSUE THREAD

**Issue by dahanmeir** [SharePoint/PnP-Sites-Core#983] opened 2017-01-19 20:14 UTC
applying files

`<pnp:Files>
        <pnp:File Src="_catalogs\masterpage\DiscountArticle.aspx" Folder="{masterpagecatalog}" Overwrite="true" Level="Published">
          <pnp:Properties>
            <pnp:Property Key="ContentTypeId" Value="{contenttypeid:פריסת דף}" />
            <pnp:Property Key="Title" Value="דיסקונט - דף כתבה" />
            <pnp:Property Key="PublishingPreviewImage" Value="{masterpagecatalog}/he-IL/Preview Images/BlankWebPartPage.png, /sites/Discount{masterpagecatalog}/he-IL/Preview Images/BlankWebPartPage.png" />
            <pnp:Property Key="PublishingHidden" Value="False" />
            <pnp:Property Key="PublishingAssociatedContentType" Value=";#דיסקונט - דף כתבה;#0x010100C568DB52D9D0A14D9B2FDCC96666E9F2007948130EC3DB064584E219954237AF39005683D58BA20548428C77C03DE5D7762E01;#" />
            <pnp:Property Key="BSN" Value="Microsoft.SharePoint.Client.FieldLookupValue" />
            <pnp:Property Key="_ListSchemaVersion" Value="60" />
            <pnp:Property Key="_Dirty" Value="0" />
            <pnp:Property Key="_Parsable" Value="1" />
          </pnp:Properties>
        </pnp:File>
        <pnp:File Src="_catalogs\masterpage\DiscountEvent.aspx" Folder="{masterpagecatalog}" Overwrite="true" Level="Published">
          <pnp:Properties>
            <pnp:Property Key="ContentTypeId" Value="{contenttypeid:פריסת דף}" />
            <pnp:Property Key="Title" Value="דיסקונט - דף אירוע" />
            <pnp:Property Key="PublishingPreviewImage" Value="{masterpagecatalog}/he-IL/Preview Images/BlankWebPartPage.png, /sites/Discount{masterpagecatalog}/he-IL/Preview Images/BlankWebPartPage.png" />
            <pnp:Property Key="PublishingHidden" Value="False" />
            <pnp:Property Key="PublishingAssociatedContentType" Value=";#דיסקונט - דף אירוע;#0x010100C568DB52D9D0A14D9B2FDCC96666E9F2007948130EC3DB064584E219954237AF39005683D58BA20548428C77C03DE5D7762E02;#" />
            <pnp:Property Key="BSN" Value="Microsoft.SharePoint.Client.FieldLookupValue" />
            <pnp:Property Key="_ListSchemaVersion" Value="60" />
            <pnp:Property Key="_Dirty" Value="0" />
            <pnp:Property Key="_Parsable" Value="1" />
          </pnp:Properties>
        </pnp:File>
        <pnp:File Src="_catalogs\masterpage\DiscountPublish.html" Folder="{masterpagecatalog}" Overwrite="true" Level="Published">
          <pnp:Properties>
            <pnp:Property Key="ContentTypeId" Value="{contenttypeid:דף HTML ראשי}" />
            <pnp:Property Key="HtmlDesignFromMaster" Value="{masterpagecatalog}/DiscountPublish.html, https://eladsystems.sharepoint.com/sites/Discount{masterpagecatalog}/DiscountPublish.html" />
            <pnp:Property Key="HtmlDesignAssociated" Value="True" />
            <pnp:Property Key="HtmlDesignStatusAndPreview" Value="{masterpagecatalog}/DiscountPublish.html, ההמרה הצליחה." />
            <pnp:Property Key="BSN" Value="Microsoft.SharePoint.Client.FieldLookupValue" />
            <pnp:Property Key="_ListSchemaVersion" Value="60" />
            <pnp:Property Key="_Dirty" Value="0" />
            <pnp:Property Key="_Parsable" Value="1" />
          </pnp:Properties>
        </pnp:File>
        <pnp:File Src="_catalogs\masterpage\DiscountWebPartsNoStrip.aspx" Folder="{masterpagecatalog}" Overwrite="true" Level="Published">
          <pnp:Properties>
            <pnp:Property Key="ContentTypeId" Value="{contenttypeid:פריסת דף}" />
            <pnp:Property Key="Title" Value="דיסקונט - דף web parts ללא strip" />
            <pnp:Property Key="PublishingPreviewImage" Value="{masterpagecatalog}/he-IL/Preview Images/BlankWebPartPage.png, /sites/Discount{masterpagecatalog}/he-IL/Preview Images/BlankWebPartPage.png" />
            <pnp:Property Key="PublishingHidden" Value="False" />
            <pnp:Property Key="PublishingAssociatedContentType" Value=";#דיסקונט - דף כללי;#0x010100C568DB52D9D0A14D9B2FDCC96666E9F2007948130EC3DB064584E219954237AF39005683D58BA20548428C77C03DE5D7762E;#" />
            <pnp:Property Key="BSN" Value="Microsoft.SharePoint.Client.FieldLookupValue" />
            <pnp:Property Key="_ListSchemaVersion" Value="60" />
            <pnp:Property Key="_Dirty" Value="0" />
            <pnp:Property Key="_Parsable" Value="1" />
          </pnp:Properties>
        </pnp:File>
        <pnp:File Src="_catalogs\masterpage\DiscountUnit.aspx" Folder="{masterpagecatalog}" Overwrite="true" Level="Published">
          <pnp:Properties>
            <pnp:Property Key="ContentTypeId" Value="{contenttypeid:פריסת דף}" />
            <pnp:Property Key="Title" Value="דיסקונט - דף יחידה" />
            <pnp:Property Key="PublishingPreviewImage" Value="{masterpagecatalog}/he-IL/Preview Images/BlankWebPartPage.png, /sites/Discount{masterpagecatalog}/he-IL/Preview Images/BlankWebPartPage.png" />
            <pnp:Property Key="PublishingHidden" Value="False" />
            <pnp:Property Key="PublishingAssociatedContentType" Value=";#דיסקונט - דף כללי;#0x010100C568DB52D9D0A14D9B2FDCC96666E9F2007948130EC3DB064584E219954237AF39005683D58BA20548428C77C03DE5D7762E;#" />
            <pnp:Property Key="BSN" Value="Microsoft.SharePoint.Client.FieldLookupValue" />
            <pnp:Property Key="_ListSchemaVersion" Value="60" />
            <pnp:Property Key="_Dirty" Value="0" />
            <pnp:Property Key="_Parsable" Value="1" />
          </pnp:Properties>
        </pnp:File>
        <pnp:File Src="_catalogs\masterpage\DiscountWebPartsWithStrip.aspx" Folder="{masterpagecatalog}" Overwrite="true" Level="Published">
          <pnp:Properties>
            <pnp:Property Key="ContentTypeId" Value="{contenttypeid:פריסת דף}" />
            <pnp:Property Key="Title" Value="דיסקונט - דף web parts עם strip" />
            <pnp:Property Key="PublishingPreviewImage" Value="{masterpagecatalog}/he-IL/Preview Images/BlankWebPartPage.png, /sites/Discount{masterpagecatalog}/he-IL/Preview Images/BlankWebPartPage.png" />
            <pnp:Property Key="PublishingHidden" Value="False" />
            <pnp:Property Key="PublishingAssociatedContentType" Value=";#דיסקונט - דף כללי;#0x010100C568DB52D9D0A14D9B2FDCC96666E9F2007948130EC3DB064584E219954237AF39005683D58BA20548428C77C03DE5D7762E;#" />
            <pnp:Property Key="BSN" Value="Microsoft.SharePoint.Client.FieldLookupValue" />
            <pnp:Property Key="_ListSchemaVersion" Value="60" />
            <pnp:Property Key="_Dirty" Value="0" />
            <pnp:Property Key="_Parsable" Value="1" />
          </pnp:Properties>
        </pnp:File>
        <pnp:File Src="_catalogs\masterpage\DiscountHome.aspx" Folder="{masterpagecatalog}" Overwrite="true" Level="Published">
          <pnp:Properties>
            <pnp:Property Key="ContentTypeId" Value="{contenttypeid:פריסת דף}" />
            <pnp:Property Key="Title" Value="דיסקונט - דף הבית" />
            <pnp:Property Key="PublishingPreviewImage" Value="{masterpagecatalog}/he-IL/Preview Images/BlankWebPartPage.png, /sites/Discount{masterpagecatalog}/he-IL/Preview Images/BlankWebPartPage.png" />
            <pnp:Property Key="PublishingHidden" Value="False" />
            <pnp:Property Key="PublishingAssociatedContentType" Value=";#דיסקונט - דף כללי;#0x010100C568DB52D9D0A14D9B2FDCC96666E9F2007948130EC3DB064584E219954237AF39005683D58BA20548428C77C03DE5D7762E;#" />
            <pnp:Property Key="BSN" Value="Microsoft.SharePoint.Client.FieldLookupValue" />
            <pnp:Property Key="_ListSchemaVersion" Value="60" />
            <pnp:Property Key="_Dirty" Value="0" />
            <pnp:Property Key="_Parsable" Value="1" />
          </pnp:Properties>
        </pnp:File>
        <pnp:File Src="_catalogs\masterpage\DiscountSystem.html" Folder="{masterpagecatalog}" Overwrite="true" Level="Published">
          <pnp:Properties>
            <pnp:Property Key="ContentTypeId" Value="{contenttypeid:דף HTML ראשי}" />
            <pnp:Property Key="HtmlDesignFromMaster" Value="{masterpagecatalog}/DiscountSystem.html, https://eladsystems.sharepoint.com/sites/Discount{masterpagecatalog}/DiscountSystem.html" />
            <pnp:Property Key="HtmlDesignAssociated" Value="True" />
            <pnp:Property Key="HtmlDesignStatusAndPreview" Value="{masterpagecatalog}/DiscountSystem.html, ההמרה הצליחה." />
            <pnp:Property Key="BSN" Value="Microsoft.SharePoint.Client.FieldLookupValue" />
            <pnp:Property Key="_ListSchemaVersion" Value="58" />
            <pnp:Property Key="_Dirty" Value="0" />
            <pnp:Property Key="_Parsable" Value="1" />
          </pnp:Properties>
        </pnp:File>
      </pnp:Files>`

**Comment by VesaJuvonen** [comment] 2017-01-20 13:21
Hi dahanmeir,
we would need environment details like requested in the Issue template to be able to do anything with this information. So - is this for on-premises or SP Online. If on-premises, what version. Which PnP version was used. Unless we can reproduce the issue, we cannot determine if the issue is in the template, PnP or native CSOM.

thx for the additional details advance.

**Comment by jansenbe** [comment] 2017-03-10 10:29
Closing this issue since we've not received feedback for a long time. We want to further investigate this, but if there's no feedback we can't. Absolutely fine for you to re-open the issue if you can still re-produce using the March 2017 release or if you have additional context that can help.

**Closed by jansenbe** 2017-03-10 10:29 UTC
Labels: waiting-for-clarification
