### ISSUE TITLE
new AuthenticationManager().GetAppOnlyAuthenticatedContext time out after 1 hour

### ISSUE THREAD

**Issue by AtDH01** [SharePoint/PnP-Sites-Core#1758] opened 2018-05-11 12:32 UTC
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Using "new AuthenticationManager().GetAppOnlyAuthenticatedContext" to create a Client Context, the context should continue running.  For example, long running operations via a console application, and not timeout after 1 hour with 401 errors.

#### Observed Behavior
When using "new AuthenticationManager().GetAppOnlyAuthenticatedContext", the session is only valid for 1 hour, this causes failures and we start seeing 401 errors.  My understanding, is that a refresh token should re-validate the session, to prevent 401 unauthorised access. 

#### Steps to Reproduce
````
using (var clientContext = new AuthenticationManager().GetAppOnlyAuthenticatedContext(SiteUrl, ClientId, ClientSecret))
            {
                try
                {
                    if (clientContext != null)
                    {
                        // Example, Get List, Get all Items, Look at permissions assigned to each item
                        for (var i = 0; i < 10000; i++)
                        {
                            var oWebsite = clientContext.Web;
                            var collList = oWebsite.Lists;
                            clientContext.Load(collList);
                            clientContext.ExecuteQuery();
                            System.Threading.Thread.Sleep(10000);
                            Console.WriteLine(string.Format("Number of lists: {0} and iteration {1}", collList.Count, i));
                        }
                    }
                }
                catch (Exception e)
                {
                    Console.WriteLine(e.Message);

                }
                Console.ReadKey();
            }

Console app will fail once running for 1 hour.

**Comment by PaoloPia** [comment] 2018-05-11 12:38
Hi @AtDH01,
Thanks for your feedback. That's how the token works, it expires. You will need to create a new one, when it expires. I will close this item, because it is not a bug.

**Closed by PaoloPia** 2018-05-11 12:38 UTC

**Comment by koskila** [comment] 2018-10-30 04:20
Sorry to comment on an old+closed issue, but I was wondering if there's a reason why the code sets the lease to 60 minutes even when the lease for the access token might be 8 hours (for example)?

I understand that refresh tokens aren't returned, so the session can't be refreshed. But sometimes it's valid for more than an hour.

This looks somewhat unintuitive to me, but I was wondering if there was a good reason for it?

```
var lease = GetAccessTokenLease(response.ExpiresOn);
lease =
 TimeSpan.FromSeconds(
  Math.Min(lease.TotalSeconds - TimeSpan.FromMinutes(5).TotalSeconds,
  TimeSpan.FromHours(1).TotalSeconds));
```
