### ISSUE TITLE
special characters in field description are not escaped

### ISSUE THREAD

**Issue by andikrueger** [SharePoint/PnP-Sites-Core#717] opened 2016-08-23 12:50 UTC
#### Category

[x] Bug
[ ] Enhancement
#### Environment

[x] Office 365 / SharePoint Online
[x] SharePoint 2016
[ ] SharePoint 2013
### Site Collection

Multi language Site Collection
#### Expected or Desired Behavior

Special characters like " are escaped in the resulting template file. 
#### Observed Behavior

Special characters are not escaped. Method ApplyProvisioningTemplate fails.
In function ProvisionObjects in ObjectField.cs the 
`XElement templateFieldElement = XElement.Parse(...` fails for the field with the special character.
#### Steps to Reproduce
1. create Field with a description like: **this is the "description"**
2. Generate a new template with this field
3. try to apply this template

**Comment by jansenbe** [comment] 2017-02-06 01:05
Hi @andikrueger ,

We can't reproduce this with the latest version. Can you confirm you still have this issue?

**Comment by jansenbe** [comment] 2017-03-10 10:23
Closing this issue since we've not received feedback for a long time. We want to further investigate this, but if there's no feedback we can't. Absolutely fine for you to re-open the issue if you can still re-produce using the March 2017 release or if you have additional context that can help.

**Closed by jansenbe** 2017-03-10 10:23 UTC
Labels: waiting-for-clarification
