### ISSUE TITLE
[Provisioning Engine] SharePoint Groups are based on Site Title which may differ for newly created sites. This could lead to an error while applying the provisioning template.

### ISSUE THREAD

**Issue by sureshbooms** [SharePoint/PnP-Sites-Core#370] opened 2016-02-12 15:05 UTC
For Community site template, the RoleAssignments (on Site Collection level as well as List Instances) are extracted based on the existing Site Title, but the new created site may have different Role names which means these cannot be found while applying the template on different site.

Suggest to use a token (e.g. {site title]) that can be replace with the new site title while applying the template on a different site.

**Comment by PaoloPia** [comment] 2016-02-22 00:05
Hi,
Thanks for your feedback. What version of the engine are you using? We fixed such kind of issue on February 4th. I'm wondering if you are using an old version of the engine, or if the issue is not yet completely fixed. Thanks.

**Comment by sureshbooms** [comment] 2016-02-22 17:27
Hi,

I have tested this against the latest version (with 2.0.1601.0).

Met vriendelijke groet / Kind Regards,

Suresh Booms
Solution Architect
v-suresb@microsoft.com<mailto:v-suresb@microsoft.com>
+31 (0)6 46 284 213

**Comment by PaoloPia** [comment] 2016-12-07 23:09
Hi,
Sorry for the delayed answer, but yes you were using an old version of the engine. This issue is fixed since February 2016. Thus, I will close this item. Thanks.

**Closed by PaoloPia** 2016-12-07 23:09 UTC
