### ISSUE TITLE
Provisioning fails in the case additional admin cannot be resolved correctly through displayname

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/PnP-Sites-Core#1051] opened 2017-02-09 16:57 UTC
_From @awdhaan on February 7, 2017 13:58_

#### Category
[X ] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[X ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 15.0.4763.1000

#### Expected or Desired Behavior
The provisioning tool should resolve the value from the “Additional admins” field into actual users and apply this data when provisioning a site

#### Observed Behavior
When creating a site request via the request form and adding “Additional admins”, provisioning fails in case there is a user account entered from Active Directory (AD) for which another account exists in AD with the exact same display name (e.g. a production user and a test user), while the account name is unique. 
In that particular scenario, the remote timer job cannot resolve a unique user when reading the display name from the "Additional Admins" field in the "Site Requests" list on the host site collection. As a result, the site is not created and an exception occurs.

#### Steps to Reproduce
Ensure two AD users exist with the exact same display name and add either one of them to the “Additional Admins” field when requesting a new site to consistently reproduce the error.

### Possible solution
When changing the “ShowField” property from the “Additional admins” field from “Name” to “Account”, the code is able to resolve a unique user without running into the exception. For the installation, the PnPSiteProvisioning.xml for provisioning the Site Request list should be updated as follows:

<Field Type="User" Name="SP_AdditionalAdmins" DisplayName="Additional Admins" ID="{8c25e50c-9d31-483c-9a6d-66bdb39bbfe4}" Group="SiteProvisioning" Mult="TRUE" UserSelectionMode="0" ShowField="Name" Description="Additional Administrators" SourceID="{e39236f6-e0b6-4d25-99b4-6e02eceb2207}" StaticName="SP_AdditionalAdmins" AllowDeletion="TRUE" />

ShowField="ImnName" should become ShowField="Name".

_Copied from original issue: SharePoint/PnP#1600_

**Comment by jansenbe** [comment] 2017-02-10 02:19
Hi @awdhaan ,

Are you using the PnP Partner Pack and having this issue? Can you be more precise on how the issue is occurring.

**Comment by awdhaan** [comment] 2017-02-10 11:10
It's the UX.Provisioning app. We noticed the issue when creating a new site and adding a particular user as additional admin. This user has another account for testing, with the exact same displayname as his primary account. Apparently, the UX.Provisioning app attempts to resolve the user by displayname, and wasn't able to do so as the primary and test account have the exact same display name. As a result of this, the site request is not proccessed.

**Comment by awdhaan** [comment] 2017-02-21 08:22
Any progress on this? Just wondering if I can help :-)

**Comment by jansenbe** [comment] 2017-03-10 10:40
Hi @awdhaan , this should be fixed in the UX.Provisioning project which is living in the PnP repository. Can you create a new issue in https://github.com/SharePoint/PnP/issues? Will close the issue in this repo since it's not an PnP Sites Core issue.

**Closed by jansenbe** 2017-03-10 10:40 UTC
Labels: waiting-for-clarification

**Comment by awdhaan** [comment] 2017-03-10 11:23
Hi @jansenbe , please liaise with @VesaJuvonen on this one. I originally posted this in https://github.com/SharePoint/PnP/issues/1600 but it was moved to the core with the following comment "...since this is directly related on the PnP Provisioning Engine, relocating this issue to PnP-Sites-Core, so that it's not getting lost."
